### ISSUE TITLE
Skybox configuration: aligned to camera vs aligned to model

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#100]

**Comment by elalish** [comment]
@cdata I believe this would not matter either way, since the radius of the skybox is generally assumed to be infinity anyway.

**Comment by cdata** [comment]
Yeah, in hindsight this only mattered because our skybox technically isn't an infinitely distant thing, so you can actually register the difference. We can probably close this.

**Comment by mrdoob** [comment]
For the record, skyboxes are always supposed to be aligned to the camera otherwise you get strange distortions.
