### ISSUE TITLE
some models are washed out

### ISSUE THREAD

**Issue by smalls** [GoogleWebComponents/model-viewer#179]
Some models appear very washed out. One example is: https://poly.google.com/view/4lZW20kkyMD?jsmode=du

Washed out version (current `<model-viewer>`):

![washed-out](https://user-images.githubusercontent.com/562883/48448150-f21b2580-e752-11e8-9436-d85a9151ecda.png)

More detail (hosted at https://poly.google.com/view/4lZW20kkyMD?jsmode=du):

![more-detail](https://user-images.githubusercontent.com/562883/48448164-fcd5ba80-e752-11e8-9b36-aa0c887e18c9.png)

We have several work items to tackle this (at a glance, #34, #6), so this may be fixed as we pick up those.

**Comment by rcabanier** [comment]
We've seen this as well. It looks like the washed-out look depends on what application exported the model.
Maybe there is a color managment issue (sRGB vs Linear?)

**Comment by jsantell** [comment]
Right now, there's only environment map and an ambient light for lighting, and models from Blocks are (all?) very rough, unmetallic materials, resulting in minimal lighting from the environment, and no directional lighting to give interesting coloration on this model, rather flat-looking model -- I think the solution here is add and expose some sort of directional light (which is what we want to add, but need to figure out a minimal set of controls to enable good lighting for all models)

**Comment by rcabanier** [comment]
We've given authors the option to increase the environment map light intensity to work around this.

**Comment by jsantell** [comment]
I don't think the envmap will help in this scenario, see these PBR cubes at 0.1, 1, and 2 envmapintensity below -- notice the bottom right sphere (roughness:1, metalness: 0, diffuse: white) -- it's fully blown out

![screenshot from 2018-11-14 10-08-29](https://user-images.githubusercontent.com/641267/48502994-c43aed00-e7f5-11e8-9791-74c204d32e7c.png)

![screenshot from 2018-11-14 10-07-46](https://user-images.githubusercontent.com/641267/48502992-c2712980-e7f5-11e8-821e-fe2339c0b817.png)

![screenshot from 2018-11-14 10-09-15](https://user-images.githubusercontent.com/641267/48502996-c69d4700-e7f5-11e8-872c-48c6e2deea11.png)
