### ISSUE TITLE
Ability to Blur out environment

### ISSUE THREAD

**Issue by jsantell** [GoogleWebComponents/model-viewer#181]
A common feature in model viewers is the ability to apply a blur on the environment. This deemphasizes the environment, makes the model pop, more interesting than a flat color, and ability to provide a nicer environment map than the default one generated. I don't think this should change the PMREM generation, such that a very reflective model would reflect the unblurred environment, but curious how other platforms handle this with regard to the corresponding environment map on the model

**Comment by mikkoh** [comment]
I think it would be interesting to go beyond blurring to be able to define what the bg looks like. Like maybe you want to use a flat color for the background but use an environment map for lighting.

**Comment by elalish** [comment]
Maybe just select a mipmap level to display? This does seem to be one of the main differences in our rendering vs filament, if we want those to be more consistent with them.

**Comment by elalish** [comment]
@cdata this is the single most obvious difference in our fidelity tests with filament, and should be quite a simple fix. Should we add this to the rendering stuff for 0.5?

**Comment by cdata** [comment]
SGTM
