### ISSUE TITLE
Background color does not accept all valid CSS strings

### ISSUE THREAD

**Issue by cwervo** [GoogleWebComponents/model-viewer#182]
Tried with `background: linear-gradient(#e66465, #9198e5);`, `radial-gradient(#e66465, #9198e5)` & `transparent`

## Suggested resolution
- For `transparent` load the underlying Three context with `{alpha: true}` add a `console.warn()` noting that setting the `alpha` of the underlying will potentially [impact performance](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#Turn_off_transparency)
- Either provide the same note as above & set the `.container`'s background-color to the CSS string, or could possibly do some static mapping version of #66 since we're already in a 3D context?

**Comment by jsantell** [comment]
You totally called our bluff on 'all valid CSS strings', Andres :grimacing: we should update that in the docs to specify that it accepts the subset of `<color>` strings supported by [THREE.Color#setStyle](https://threejs.org/docs/#api/en/math/Color.setStyle). Although it doesn't seem too outrageous to parse out gradients, I wonder if there's some combo of specifying a set of colors and generating something like #66 (for that blurry effect commonly used, e.g. #181)

**Comment by forresto** [comment]
Are there any blockers to making a new `transparent` attribute on the custom element, that uses Three's `{alpha: true}`? I can try to make a PR if that sounds good.

**Comment by mrdoob** [comment]
@forresto a PR to test the idea out would be nice indeed 👌

**Comment by forresto** [comment]
To test I set `this.skysphere.visible = false;` ... would there need to be more logic around that? There are a few place that expect the skysphere to exist.

With `this.renderer.autoClear = false;` other models on the page and trails:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/395307/49661880-5363ab00-fa18-11e8-89cf-b50270f10359.png">

With `this.renderer.autoClear = true;` gets rid of the other models, but still leaves these trails... any hints?

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/395307/49661266-a0df1880-fa16-11e8-9d44-ad1f8696f3bb.png">
