### ISSUE TITLE
Generated Models

### ISSUE THREAD

**Issue by Martin-Pitt** [GoogleWebComponents/model-viewer#186]
### Description

Similar request as https://github.com/keithclark/3d-model-element/issues/7 – how would `<model-viewer>` handle procedurally generated 3D models locally from the client?

• Is there an API?
• Or would we have to encode a 3D model, pass to `URL.createObjectURL` and then the URL into `<model-viewer>` which then has to decode the 3D model?

The latter seems like it could work technically, but laggy or suboptimal. A popular usecase for example could be product customisation with dropdowns options.

It seems to put a heavy emphasis on server-loaded 3D models right now.

**Comment by jsantell** [comment]
Currently, you'd have to use the `URL.createObjectURL` method or a base64 data URI (haven't tried though). This should not have any affect on decoding or responsiveness. What is "decoding" in this case? "Procedurally generated models" is very broad -- are you talking about generating mesh and material data? That will have to be structured in some format to be 'decoded', and right now the API contract is the glTF spec -- that being said, this is all just the current state of a very nascent and new project and anything can change.

GLTF supports "scenes", which could handle multiple configurations/iterations of a model, possibly a more immediately tangible feature.

**Comment by cdata** [comment]
@Martin-Pitt we definitely want to enable use cases like product customization. _How_ we enable them is still a fairly open question.

One of the strengths that we want to showcase in `<model-viewer>` is that it makes presenting a 3D model on the web as easy as presenting a 2D image.

Some of the features we are planning might help customization without exposing the underlying scene graph to imperative manipulation. In this vein, one thing that we might look into eventually is declarative material configuration.

OTOH it's possible that we could give users unfettered access to the underlying Three.js scene. If we did this, users could procedurally generate anything that they could already generate with Three.js.

However, low-level access like this creates a risk that `<model-viewer>` could become harder to use over the long run. If users regularly have to use the Three.js API to accomplish practical goals, why shouldn't they just use Three.js on its own?

So to the extent that it is feasible, we would like to explore how to achieve a lot of customization without requiring users to jump down to a lower-level API.
