### ISSUE TITLE
Accessibility: keyboard support

### ISSUE THREAD

**Issue by vcastrejont** [GoogleWebComponents/model-viewer#187]
### Description
A good way to start with the accessibility is to add keyboard support for the component

#### Expected behavior
When web component has focus user can rotate the model using arrow keys
- Left arrow will rotate the model to the left
- Right arrow will rotate the model to the right
- Up arrow will rotate the model up
- Down arrow will rotate the model down
- Page down will zoom out the model
- Page up will zoom in the model

On mac laptops fn+up key is a shortcut for page up also fn+down is shortcut for page down.

### Browser Affected
- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] Helios
- [x] IE
- [x] Safari

### OS
- [ ] Android
- [ ] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### Versions
- model-viewer: v0.0.4
- three.js: r0.94.0

**Comment by smalls** [comment]
We're looking at the three sub-issues; we believe those should address this.

**Comment by cdata** [comment]
This has been addressed over the course of implementing #222, #223 and #224. Thanks for calling attention to this issue!
