### ISSUE TITLE
Lint Failing

### ISSUE THREAD

**Issue by mikkoh** [GoogleWebComponents/model-viewer#189]
### Description

Hate to do this. Cause it's really a nit and nothing to do with functionality.

Noticed that `eslint` is failing all over the place. I use VS Code and I have the eslint plugin and it's pretty annoying to contribute. When you see it failing all over the place.

I can totally start to clean this stuff up but it's gonna be pretty extensive 😬 

An example of what it looks like for me to edit some files. In this screenshot the red squiggles are portions of code failing linting.

### src/model-viewer-base.js
<img width="516" alt="screen shot 2018-11-14 at 2 54 29 pm" src="https://user-images.githubusercontent.com/496903/48508693-35da6180-e81d-11e8-8722-1ac658a7f72c.png">

**Comment by jsantell** [comment]
The lint file is vestigial from a previous iteration, I think -- we've been using the `.clang-format` tool here in lieu of linting (pushing responsibility to a tool rather than devs). I think we can remove the lint file, WDYT @cdata?

**Comment by mikkoh** [comment]
If you want to keep eslint you could add `"require-jsdoc": ["off"]` to `.eslintrc` this will reduce a lot of the noise.

I recognize at some point you might want to 🔥 /delete `"require-jsdoc": ["off"]` but it might be a nice thing to do now.

**Comment by cdata** [comment]
We can probably nix the eslint config in the short term, rely on clang-format for now and eventually apply tslint once we move to TypeScript. It would be fine to make eslint work in the near term if the change is relatively trivial.
