### ISSUE TITLE
Improve error message when model file requires DRACO

### ISSUE THREAD

**Issue by mrdoob** [GoogleWebComponents/model-viewer#194]
The component currently doesn't support files with DRACO compression and the error message in the console is not very descriptive.

<img width="674" alt="screen shot 2018-11-15 at 2 11 19 pm" src="https://user-images.githubusercontent.com/97088/48585851-cf1f7b80-e8e2-11e8-8feb-b98565995680.png">

**Comment by jsantell** [comment]
Fixed via https://github.com/GoogleWebComponents/model-viewer/commit/f64a6de8c007bbc57eea666dec1f66058b320abb ?

**Comment by smalls** [comment]
![error](https://user-images.githubusercontent.com/562883/48649336-2c7d0080-e9a7-11e8-8a51-4729896d9e90.png)

I think that change fixed it up. Thanks!
