### ISSUE TITLE
Adjustable camera FOV

### ISSUE THREAD

**Issue by jsantell** [GoogleWebComponents/model-viewer#232]
Currently, this is set to 45 degrees, with a robust rationale of "this looked good for some test models awhile back" -- of course there's not a one-size-fits-all, so this will need to be configured. Here's an example of zooming in on a long model, where the spheres on the sides really start to bend due to the small FOV:

![screenshot from 2018-11-20 17-25-45](https://user-images.githubusercontent.com/641267/48812945-818f7e00-ece9-11e8-888f-6f4e29ef4204.png)

**Comment by johnpallett** [comment]
It would be good if developers could control this, but there's also room for automatic adjustment based upon the distance from model geometry, i.e. as you get closer to the geometry it may make sense to widen the FOV instead of physically getting nearer

**Comment by elalish** [comment]
I take it the current setting is 45 deg vertical FOV? As a start we could set FOV to 45 for the widest direction. I agree that it should be configurable.
