### ISSUE TITLE
Banding artifacts

### ISSUE THREAD

**Issue by jsantell** [GoogleWebComponents/model-viewer#239]
### Description

I think this started occurring with https://github.com/GoogleWebComponents/model-viewer/pull/227, possibly due to the change of EquirectangularToCubeGenerator. It's observable for brief moments in the fuzzer when changing out resources quickly.

![artifacts](https://user-images.githubusercontent.com/641267/49172883-07698580-f2f7-11e8-8058-146617af6cfb.png)

Of course the fuzzer isn't a realistic test case, so not sure how big of a deal this is in practice, but it is peculiar and unexpected.

@mrdoob had a hunch that it could be from setting a normal map -- although the sphere pictured does not have one, other models previously loaded (DamagedHelmet) certainly has a normal map. "These artifacts look like what you see when you zoom too much in a derivatives-based normal mapping."

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
@cdata Do you know how to reproduce this? I've made enough rendering changes I wonder if it hasn't been fixed accidentally by now.

**Comment by mrdoob** [comment]
I *think* this can be closed now.

**Comment by cdata** [comment]
I have never reproduced this issue myself. I think it's safe to close and we can re-open if we manage to reproduce it.
