### ISSUE TITLE
Can we derive better default aria-label text?

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#244]
Referencing discussion here: https://github.com/GoogleWebComponents/model-viewer/pull/242#discussion_r237312846

Right now we have a static default aria-label text on the canvas. It updates if the user configures alt text, but it's possible that we could derive better defaults based on other configurations such as the URL. This issue is for discussing potentially richer defaults.

**Comment by mikkoh** [comment]
Is this issue still valid? I see the `aria-label` being dynamically updated even when the user is interacting with the canvas.
