### ISSUE TITLE
add (and clean up existing) documentation

### ISSUE THREAD

**Issue by smalls** [GoogleWebComponents/model-viewer#259]
Clean up our current documentation (mostly in README.md and examples/*) into a set of docs focused on helping new users with key use cases.

Note that there may be benefit to preserving what's currently in examples/* as it's initial purpose as a set of tests.

**Comment by smalls** [comment]
As part of #320, we're pushing more documentation our of `README.md` and into `index.html`. Right now there's duplication, but as part of this let's take a consolidation pass to make sure the organization makes sense.

**Comment by cdata** [comment]
I'm going to call this one closed as of #402 . Feel free to re-open if y'all disagree!
