### ISSUE TITLE
Create realistic, real-world scale model that works for AR

### ISSUE THREAD

**Issue by johnpallett** [GoogleWebComponents/model-viewer#270]
We don't currently have a good demo model that looks realistic, is centered at the origin (with the base of the object at the origin). This would be great for AR demos. Ideally a .glb and a .usdz would be useful.

**Comment by cdata** [comment]
This has been completed in this demo: https://zircon-jeep.glitch.me

**Comment by darkvertex** [comment]
@cdata hi! I was wondering... what is the secret to knowing what scale your glb is going to be in the real world?

Is there an equivalency like 10 3D "units" = "10cm in real world" AR, or something like that?

**Comment by cdata** [comment]
@darkvertex great question. [The glTF spec is very clear on this point](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units):

 > The units for all linear distances are meters.

All units in your `.gltf` or `.glb` file are specified in real-world meters. That's how we treat them when presenting a model in WebXR-based AR. That's also how Scene Viewer treats them. And any viewer that doesn't treat them that way is wrong (according to the spec) 👍
