### ISSUE TITLE
frame.getDevicePose is renamed to frame.getViewerPose

### ISSUE THREAD

**Issue by sorskoot** [GoogleWebComponents/model-viewer#286]
### Description

Just ran into an issue where the models couldn't be viewed in AR on Chrome Canary anymore. This was working a few weeks ago. After some debugging and digging I found that `frame.getDevicePose` was renamed to `frame.getViewerPose` in the spec and also in Chrome Canary. As you can read in this commit: https://chromium.googlesource.com/chromium/src.git/+/b0e5777b6203aaebf30596ba76c424626ae4a720

![image](https://user-images.githubusercontent.com/2283621/50715172-47e9bb00-107c-11e9-9bd3-69848313de1b.png)

#### Live Demo
https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html

### Browser Affected

- [X] Chrome (Canary version 73.0.3660.2)
- [ ] Firefox
- [ ] Helios
- [ ] Edge
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.0.6
- three.js: r0.99.0

**Comment by cdata** [comment]
Thanks for reporting! We'll try to get in a fix before the next release.

Contributions are always welcome as well! 😀

**Comment by mrdoob** [comment]
@cdata he already did a PR for it: #287

**Comment by cdata** [comment]
:+1: missed that, thanks @mrdoob !
