### ISSUE TITLE
Presence of camera controls announced by visual prompt

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#317]
_As a web content viewer,
when I focus on a `<model-viewer>`,
I would like to be told about the camera controls,
so that I know that I can interact with it_

This is a sub-issue of #299

**Comment by cdata** [comment]
@yuinchien made some very nice mocks for potential visual prompts

Touch input|Keyboard input
------------|---------------
![image](https://user-images.githubusercontent.com/240083/51954865-b1988300-23f6-11e9-8363-0f804ea42831.png)|![image](https://user-images.githubusercontent.com/240083/51954866-b1988300-23f6-11e9-8065-0cb787d63237.png)

I have been working on an animated SVG version of these:

![image](https://lopsided-motion.glitch.me/test.svg)

**Comment by yuinchien** [comment]
This is amazing! Love it~ 

I wonder if the arrow can have rounded tip, and do a bit 3D rotation trick that you pulled off with the curves.
