### ISSUE TITLE
Cache generated environment map

### ISSUE THREAD

**Issue by jsantell** [GoogleWebComponents/model-viewer#336]
### Description

Currently any model that uses the default environment map will each generate their own, but they're all identical. IIRC the original intention was possibly to have multiple tints, or different parameters to tweak the default environment. Since that's not yet the case, we should probably cache it, probably in the TextureUtils for now.

**Comment by elalish** [comment]
@cdata, as I was debugging it seems this has already been fixed, as this is now cached. However, if we apply a PMREM pass to it, that is applied once for each model (using the same cached environment as input, but generating a new PMREM texture).
