### ISSUE TITLE
Background image persists even after it's changed to a non-existent image

### ISSUE THREAD

**Issue by smalls** [GoogleWebComponents/model-viewer#366]
### Description

One of the cases exercised by the [background-image demo](https://googlewebcomponents.github.io/model-viewer/examples/background-image.html) is changing from a specified, valid background image to a non-existent image.

However, although it's hard to see in the sample (since it toggles through several states) the starting background image persists even when the image is set to empty.

#### Live Demo
https://harmonious-hide.glitch.me/
https://glitch.com/edit/#!/harmonious-hide

### Browser Affected
- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.0.7

**Comment by smalls** [comment]
Hat tip to @mrdoob for noticing

**Comment by elalish** [comment]
Looks like this got fixed at some point.
