### ISSUE TITLE
Failure to render glTFs with animations

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#371]
`<model-viewer>` cannot render the [Khronos Brain Stem sample glTF](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BrainStem). It fails with the following exception before anything is drawn:

![image](https://user-images.githubusercontent.com/240083/52918968-29e5bc00-32b2-11e9-8209-dd50de8d6d01.png)

The failure is on a call to update the model's skeleton: `object.skeleton.update();`.

Notably, this is a sample model with a built-in animation.

This bug was discovered while pursuing #360

**Comment by cdata** [comment]
This same issue occurs when trying to load the [Khronos Cesium Man sample glTF](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan). It's probably animation related.

**Comment by cdata** [comment]
Ditto: [Khronos Monster sample glTD](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Monster)

**Comment by jsantell** [comment]
Looks like we have a SkinnedMesh without any `skeleton`
