### ISSUE TITLE
Bad render results for KHR_materials_unlit Khronos test model

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#374]
The [Khronos Unlit Test sample model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/UnlitTest) README says that for the test model using this extension:

> The visible surface ... should appear as a uniform color, so much so that the 3D effect is intentionally lost.

And offers the following as examples of good and bad render results:

Good | Bad
------|-----
![image](https://user-images.githubusercontent.com/240083/52973400-d8513600-3372-11e9-97a5-67d7e3574643.png)|![image](https://user-images.githubusercontent.com/240083/52973413-e1420780-3372-11e9-889b-70a78dcbb5b7.png)

Here are examples of how `<model-viewer>` renders this model w/ various settings, all if which seem incorrect (possibly for different reasons):

model only|HDR `background-image`|`experimental-pmrem`
-----------|--------------------------|-----------------------
![image](https://user-images.githubusercontent.com/240083/52973636-8eb51b00-3373-11e9-9ca2-2c070ecac74c.png)|![image](https://user-images.githubusercontent.com/240083/52973650-9a084680-3373-11e9-957c-0813354df7fc.png)|![image](https://user-images.githubusercontent.com/240083/52973671-a9878f80-3373-11e9-8798-b797c2b2f5c8.png)

I also tested to see how Filament's `gltf_viewer` handles this case. It seems to handle the model correctly (presumably it supports the `KHT_materials_unlit` extension).

Filament `gltf_viewer`|
----------------------|
![image](https://user-images.githubusercontent.com/240083/52973721-d89e0100-3373-11e9-88cc-1ce3714c36a6.png)|

**Comment by donmccurdy** [comment]
The viewer will need to avoid setting .envMap on MeshBasicMaterial - that material type is not subject to all the limits of the glTF unlit material, and adding the envMap will “break” it. Not sure what’s going on in the “model only” case though.

**Comment by jsantell** [comment]
> The viewer will need to avoid setting .envMap on MeshBasicMaterial - that material type is not subject to all the limits of the glTF unlit material, and adding the envMap will “break” it. Not sure what’s going on in the “model only” case though.

A "default" env map is created in that case, leading to the "lit" appearance there. For PMREM, this is all black since an unlit material doesn't know what to do with a PMREM environment map
