### ISSUE TITLE
Bad render results for Alpha Blend Mode test model

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#381]
As of #360 , we will be including the [Khronos Alpha Blend Mode Test model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) in our fidelity tests. Unfortunately, `<model-viewer>` seems to produce incorrect render results in four out of five cases tested by the model:

`<model-viewer>`|Filament `gltf_renderer`|Khronos' example
-------------------|------------------------|------------------
![image](https://user-images.githubusercontent.com/240083/53075029-1482b480-34a1-11e9-8b12-de60d65b2df5.png)|![image](https://user-images.githubusercontent.com/240083/53075049-1f3d4980-34a1-11e9-9ba1-cd6a4c47de63.png)|![image](https://user-images.githubusercontent.com/240083/53075082-31b78300-34a1-11e9-9e08-9503b8cd8eb0.png)

**Comment by donmccurdy** [comment]
I'm confused by this result – it shows up correctly in my threejs-based viewer: https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/AlphaBlendModeTest/glTF/AlphaBlendModeTest.gltf

<img width="1017" alt="screen shot 2019-02-20 at 7 23 57 am" src="https://user-images.githubusercontent.com/1848368/53102482-98a85c80-34e0-11e9-8df7-21dafe8aa4a3.png">

**Comment by donmccurdy** [comment]
Result also looks more correct in the https://truthful-roof.glitch.me demo –

<img width="1218" alt="screen shot 2019-03-06 at 12 51 58 pm" src="https://user-images.githubusercontent.com/1848368/53912882-c9bf7b80-400e-11e9-9a5d-4245d36adb84.png">

I'm wondering if the `scene.clone()` call used inside `<model-viewer/>` has lost some information...

**Comment by cdata** [comment]
If it's useful, the live test using `<model-viewer>` is here: https://googlewebcomponents.github.io/model-viewer/test/fidelity/khronos-AlphaBlendModeTest/

It does look like the automation screenshot results in artifacts that are not present in the live render. Screenshot of live render as of now looks like https://truthful-roof.glitch.me:

![image](https://user-images.githubusercontent.com/240083/53914378-57e93100-4012-11e9-8bcb-6bb8b64f386c.png)

Still, I think it's fair to say that it is wrong (otherwise we would see more checkmarks).

**Comment by donmccurdy** [comment]
Agreed! Also possible related: https://github.com/mrdoob/three.js/issues/15483

**Comment by cdata** [comment]
This was fixed in #423
