### ISSUE TITLE
Add browser/polyfill support tables to online documentation

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#405]
During the docs update in #402 , we discussed adding more user-friendly icons to our polyfill support table.

After some horse trading, we agreed to add a prettier version of the support table to our online docs. The main rationale for not adding the prettier icons to our markdown docs was to preserve the document's legibility outside of Github.

@yuinchien suggested we could use these icons as an alternative to emoji:

https://icons.googleplex.com/#icon=ic_check_circle&search=check
https://icons.googleplex.com/#icon=ic_warning&search=warning

We may also need additional icons, depending on where we finally land with changes in #402.

**Comment by cdata** [comment]
After some discussion, we decided that it would be ideal for the tables to live in only one place. So, as part of adding the table to the docs site, let's also remove it from the POLYFILLS.md document.

**Comment by yuinchien** [comment]
#415

**Comment by cdata** [comment]
Closed by #415
