### ISSUE TITLE
Broken links to GitHub example pages

### ISSUE THREAD

**Issue by donmccurdy** [GoogleWebComponents/model-viewer#412]
When visiting several example pages, the GitHub link in the upper right goes to a 404 page:

- https://googlewebcomponents.github.io/model-viewer/examples/lighting-and-environment.html
- https://googlewebcomponents.github.io/model-viewer/examples/lazy-loading.html
- https://googlewebcomponents.github.io/model-viewer/examples/format-support.html

**Comment by cdata** [comment]
Oops =.=
