### ISSUE TITLE
Support for realtime shadows

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#418]
Currently our shadow is static. It is generated once up front, and can never change. Let's add support for realtime shadows (should be easy as they are built-in to Three.js).

**Comment by mrdoob** [comment]
Do you mean updating the floor shadow when a model is animated?

**Comment by cdata** [comment]
Yes

**Comment by pushmatrix** [comment]
@mrdoob Is this why you were playing around with those soft-shadows the other day :P

They looked pretty impressive! The default shadows inside model-viewer are pretty meh, so soft shadows would be an amazing addition.

I'm curious how ARQuickLook generates them. Is it done every time you load the view, or do they cache them. Seems like they don't update in realtime:

![shadow-usdz](https://user-images.githubusercontent.com/190692/54306031-e0317e00-459e-11e9-9064-2c073c2a0f26.gif)

**Comment by pushmatrix** [comment]
Oh silly me, I just noticed this now: https://github.com/GoogleWebComponents/model-viewer/issues/419

**Comment by cdata** [comment]
@pushmatrix yes per #419 we are planning to implement @mrdoob 's soft shadow hack as a feature of `<model-viewer>`. We are about to open a change that enables animations, and there is a high chance that realtime soft shadows will be supported (of course, with some accompanying performance cost compared to static shadows).

**Comment by mrdoob** [comment]
> @mrdoob Is this why you were playing around with those soft-shadows the other day :P

😇

**Comment by elalish** [comment]
Fixed by #513
