### ISSUE TITLE
Soft shadows

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#419]
It would be awesome if we could automatically generate soft shadows. There would be performance consequences to doing this (compared to hard, or static, shadows). Let's discuss!

**Comment by mrdoob** [comment]
I have a silly idea for this...

It's an extension to our current implementation. It involves rendering part of the object and accumulate the resulting shadow.

Happy to explain to you or @jsantell if you want to give it a go.

**Comment by cdata** [comment]
@mrdoob that sounds really interesting. I would love to hear more :)

**Comment by cdata** [comment]
@mrdoob built a prototype and shared with us: https://jsfiddle.net/mrdoob/kyu9qvb6/show/

Looks feasible to implement in the context of `<model-viewer>`

**Comment by pushmatrix** [comment]
How's this coming along?

**Comment by pushmatrix** [comment]
Just spoke with @cdata about it in more detail, and we'd really love to see this feature. The majority of use-cases we see don't require animations, so the perf hit would be negligible as the shadow would just be rendered once.

What's the likelihood of this making it on the roadmap?

**Comment by mrdoob** [comment]
Happy to allocate some time for this (for non-animated models) as long as someone else can finish the PR (refactor, add tests, etc).

**Comment by elalish** [comment]
Fixed by #513
