### ISSUE TITLE
iOS Medium App is capable of using AR Quicklook

### ISSUE THREAD

**Issue by jakecjones** [GoogleWebComponents/model-viewer#420]
Some know that not all iOS apps support AR Quicklook. I just found out that [medium.com](https://medium.com/) launched a new version of their app that is able to utilize the iOS AR Quicklook viewer. Chrome and Firefox apps do not incorporate this, is this something we need to request from Apple or all the iOS browser apps to integrate? 

I included an image of the medium browser and possibly found some iOS documentation. I'm not super versed in filing bugs but I wanted to make sure this information was being relayed.

### Apple Quicklook Documentation
https://developer.apple.com/documentation/quicklook/qlpreviewcontroller

![img_1f89209a7cff-1](https://user-images.githubusercontent.com/31197056/53986637-9b57a400-40d3-11e9-8136-33ae5693bd40.jpeg)

### Browser Affected

- [x ] Chrome
- [x ] Firefox
### OS

- [x ] iOS

**Comment by cdata** [comment]
Hi @jakecjones thanks for sharing this information with us. I have to admit, I'm not entirely sure what you are asking of us here. Are you using `<model-viewer>` on Medium and trying to get it to work with Quick Look via the Medium app?

If you could be more specific about how you are using `<model-viewer>`, that would be very helpful. Thanks!

**Comment by jakecjones** [comment]
So sorry if the first comment wasn't making much sense.

I guess i'm trying to better understand the AR compatibility of `<model-viewer>` as it pertains to alternative  iOS browsers i.e. chrome, firefox, ect. `<model-viewer>`'s implementation of the AR quicklook viewer only works with Safari and the Medium browser as of right now. 

Do you know if there is a game plan for using the `<model-viewer>` AR feature in the other iOS browsers that do not support AR quicklook?

**Comment by cdata** [comment]
@jakecjones in the grand scheme of things, if it is _possible_ to launch AR Quick Look from a browser on iOS, we would like to support it. If you find that there are browsers where launching AR Quick Look is supported, but `<model-viewer>` doesn't work as expected, please let us know and we will schedule work to get that fixed.

**Comment by cdata** [comment]
Also worth noting: we currently test iOS Safari only. So, to the extent that other browsers change their behavior, there is a chance that we will regress without knowing about it. This is something we'll have to look into testing better as time goes on.

**Comment by jakecjones** [comment]
Thanks for taking the time to respond. That for sure helps me understand more about `<model-viewer>` and how it fits in with everything I'm asking about. I'm super excited for all of this! :)
