### ISSUE TITLE
404s on the docs page

### ISSUE THREAD

**Issue by smalls** [GoogleWebComponents/model-viewer#427]
There are some 404 errors on our documentation page (https://googlewebcomponents.github.io/model-viewer/index.html)

![Screenshot 2019-03-12 at 15 26 19](https://user-images.githubusercontent.com/562883/54301920-1e1daa80-457d-11e9-8174-defc97d1e717.png)

**Comment by smalls** [comment]
The diagnosis was easy, we're referring to built resources, but the current gh pages is raw source (without any build steps).

Two thoughts:
1) Change references to unpkg.com.
2) Change the docs either to an external site backed by a built version, or still use gh-pages out of a built branch with all the build outputs checked in.

I'm leaning towards the first option.

**Comment by smalls** [comment]
Strike all of that comment above - @cdata just told me there is a build step before the deploy to gh-pages. Nice!

**Comment by cdata** [comment]
Fixed by #428
