### ISSUE TITLE
Update gltf_renderer to use Filament's new gltfio library

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#434]
@prideout tells us that their `gltf_viewer` sample that `gltf_renderer` was based on has been updated to use the new library.

**Comment by smalls** [comment]
Looks like the change is here: https://github.com/google/filament/commit/7bc6b3c818204d606192efa4c833ce520f5f4d07

**Comment by Giorat** [comment]
What does this mean? It means that model-viewer will use Filament wasm to show models?

**Comment by cdata** [comment]
No, we do comparisons to Filament as part of our fidelity test suite: https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html

**Comment by elalish** [comment]
Also, filament's TangentNormal test from Khronos is broken, and the fix is in gltfio.
