### ISSUE TITLE
Controls SVG discoverable by VoiceOver on iOS

### ISSUE THREAD

**Issue by svinkle** [GoogleWebComponents/model-viewer#446]
### Description

When using swipe gestures with VoiceOver & Safari on iOS, the controls SVG is discoverable and announced as, _"image"_. This announcement may lead to a confusing user experience as there's no further information on why the image exists. Further, it creates an unexpected and unnecessary "tab-stop."

Adding `focusable="false"` and `aria-hidden="true"` directly onto the `svg` element removes this extra tab-stop from occurring.

```html
<!-- controls-svg.js -->
<svg … focusable="false" aria-hidden="true">
  <!-- … -->
</svg>
```

![IMG_0003](https://user-images.githubusercontent.com/1392632/54942861-5ff80a80-4f06-11e9-849f-596f1f2d05d2.PNG)

#### Live Demo
1. Go to [`<model-viewer>`](https://googlewebcomponents.github.io/model-viewer/index.html) with Safari for iOS
2. Load up [VoiceOver screen reader](https://support.apple.com/en-ca/guide/iphone/turn-on-and-practice-voiceover-iph3e2e415f/ios)
3. Swipe right with one finger until the _"image"_ content is found

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.1.1

**Comment by cdata** [comment]
Great catch, thanks for filing!
