### ISSUE TITLE
Configuration to control camera target

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#453]
As of #452 , we will support user configurable camera orbit positions. However, this is limited because the camera will always face the same target (currently fixed to the scene origin).

We should support an attribute (perhaps called `camera-target`) that allows this "target" to be changed.

**Comment by elalish** [comment]
This is dependent on #214

**Comment by cdata** [comment]
The ship has sailed on #214 to some extent (specifically, it sailed when we shipped `camera-orbit` in #452 ).

My sentiment here is that we should follow a similar strategy to what we did in `camera-orbit`. The value should support 1, 2 and 3-term forms, and the 3-term form corresponds to coordinate in 3-dimensional space.

For starters, the only unit we need to support is meters.

We can probably use most of the parsing / conversion code we wrote for #452 to handle this case.
