### ISSUE TITLE
Ability to disable camera interpolation when changing camera orbital position

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#454]
As of #452 users can configure the current camera orbital position with an attribute. By default (and partially as a consequence of how camera control works generally), when the position is configured to a new value, the camera interpolates to the new position (only on subsequent changes, not for the initial value).

This is a sound default, but we should also offer a way for users to opt out of this interpolation if they wish.

**Comment by elalish** [comment]
As part of #526, I added a jumpToTarget() method on SmoothControls for this purpose internally. Perhaps we can use that.

**Comment by elalish** [comment]
It's now called jumpCamera(), and it's a public method, so I'm tempted to close this as fixed when we merge #526.

**Comment by cdata** [comment]
This is a feature issue so unless it's user-facing we should not close it.

**Comment by BassamHajjage** [comment]
3 years on, when using the example provided in docs (see below), and allowing `camera-controls`, the interpolation is still forced on the user even while changing positions. Maybe I misunderstood how to use the method?
![image](https://user-images.githubusercontent.com/85369725/162553381-f81f3ab6-e180-4a49-8871-2132dea45ee9.png)

**Comment by elalish** [comment]
I can't figure out what you're trying to achieve. What is "the method"? Can you show what the desired behavior is and what behavior you're getting instead? Also, please open a new discussion, since closed issues are not very visible.
