### ISSUE TITLE
Don't start rotating the model before the poster is dismissed

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#467]
### Description

If you have `auto-rotate` on with a poster, the model will start rotating before the poster is dismissed. The better behaviour would be for the model to only start rotating once it is visible. That way the initial pose of the model will be consistent.

This is especially important if you want the poster to be an image of the initial pose, so that it transitions smoothly from image to model.

#### Live Demo
Try it out here. Wait 5-10 seconds before clicking the poster, and you will see the astronaut has already rotated a fair bit
https://codepen.io/pushmatrix/pen/BEoExG

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] Helios
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### Versions
All versions

**Comment by cdata** [comment]
Great catch, thanks for filing!
