### ISSUE TITLE
Observable event indicating that the camera position changed

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#506]
As of #288 , we have the internal notion of a `change` event associated with `SmoothControls` moving around the camera.

As of #452 , the camera position is controlled exclusively by `SmoothControls` for all practical purposes.

As of #469 , we will also have the internal notion of camera changes due to user interaction (vs changes due to imperative API calls).

As part of https://github.com/GoogleWebComponents/model-viewer/pull/469#discussion_r272771427, we discussed including a publicly observable event that maps 1-to-1 with our internal `change` event. We haven't agreed on a name, but we should implement this event so that content authors using `<model-viewer>` can be made aware of such changes when they care to observe them.

One use case that came up recently is that for building testing tools, it would be really helpful to be able to coordinate the camera positions across multiple `<model-viewer>` elements in a single page. As of right now, this would be very hard to do, but an observable event notifying of the camera position changing would make this pretty trivial to do in the context of a dev tool.

**Comment by cdata** [comment]
We should also annotate the event detail with the following:

 - Source (e.g., user interaction or not)
 - If the source is user interaction, was it keyboard, mouse, touch?

**Comment by pushmatrix** [comment]
The source would be really really helpful.

Would you see the event firing each frame it changes? Otherwise, would it fire when the camera change starts and change ends?

**Comment by cdata** [comment]
Right now, it should fire with each incremental movement of the camera. The events would correlate with each new value reported by `getCameraOrbit()` while the camera is transiting to its destination.
