### ISSUE TITLE
npm run dev doesn't pick up changes to fidelity tests

### ISSUE THREAD

**Issue by elalish** [GoogleWebComponents/model-viewer#515]
### Description

When npm run dev is running, it seems to only pick up changes to model-viewer, but not to the other targets like image-comparison-app that the fidelity tests use. This is confusing, as all of these targets are served to 8000, but they simply don't update when changed. Also, it starts throwing Middlewear errors on the command line.

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] MacOS
- [ ] Windows

### Versions
master, as of May 1st, 2019.

**Comment by cdata** [comment]
Yeah, I agree this is confusing (or at least unexpected).

In general, it seems as though the `npm run dev` workflow loses the ability to recompile based on discrete bundle changes (it invokes some form of `npm run build` when files change, which rebuilds everything).

If I run `tsc -w` in one terminal and `rollup -c -w` in another terminal, a rebuild only occurs for the bundle (or bundles) that are affected by discrete file changes. It would be nice if we could have this property in `npm run dev` as well, that way we would not have to pick between _just_ building `model-viewer.js` and rebuilding the whole world when going that route.

**Comment by elalish** [comment]
If that's not hard, I'd agree that would be ideal. However, it's also quite easy to work around, so we could just take the tack of just updating the README to say that npm run dev only updates model-viewer and you have to do npm run build first and after any change outside of model-viewer (which is probably rare anyway).
