### ISSUE TITLE
Quality test web page results are stretched

### ISSUE THREAD

**Issue by johnpallett** [GoogleWebComponents/model-viewer#517]
### Description

The images at [https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html](https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html) are stretched

#### Live Demo
https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html

### Browser Affected
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by cdata** [comment]
Dupe of #508 and already fixed in #516
