### ISSUE TITLE
Change fidelity tests to use new default environment lighting

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#521]
When we added Khronos models to our fidelity tests in #360 , we made a decision to use an environment map when staging most of them because our default environment lighting was pretty bad and Filament had no default IBL. As of #472 we have much improved default lighting conditions in `<model-viewer>`. We should change the environment lighting used in our tests to be based on the new default.

**Comment by cdata** [comment]
Here is an archive containing the equirectangular HDR environment map equivalent of the default lighting currently being used in `<model-viewer>`: [lightroom_14b.zip](https://github.com/GoogleWebComponents/model-viewer/files/3138429/lightroom_14b.zip)

The three files included are:

 - `lightroom_14b.exr` - original, in EXR format
 - `lightroom_14b.hdr` - converted to HDR format
 - `lightroom_14b_offset.hdr` - HDR offset by 90º

**Comment by elalish** [comment]
@cdata I'm guessing we'll still want to keep a few with other environment maps, just for breadth of testing, right? Anyway, this also seems like good fodder for the 0.5 rendering work.
