### ISSUE TITLE
Sometimes modelIsVisible is wrong, causes autoRotate to break

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#524]
We have observed under some circumstances that `modelIsVisible` is incorrect, which in turn can cause `autoRotate` to break (because rotation does not occur until the model is visible as of #471 ).

**Comment by cdata** [comment]
Moving this to v0.6.0. After discussion with @elalish there is some awkwardness and subtlety to the concept of `modelIsVisible` and we probably need to re-evaluate it on a more fundamental level.

**Comment by pushmatrix** [comment]
I've seen behaviour where the model is not visible if the viewer was initially hidden and then made visible. This is a common design for online stores where you have one big product photo that you can switch by pressing thumbnails in a gallery.

However sometimes the model viewer shows blank when I change thumbnails (hide/unhide viewers). 

![gif](https://user-images.githubusercontent.com/190692/60614955-040e0f00-9d9c-11e9-8de9-c3c71feacbeb.gif)

@cdata suggested this may be related to `modelIsVisible`.  

Steps to reproduce:
- Go here https://third-dimensions.myshopify.com/products/model
- Press the second thumbnail
- The model viewer doesnt display anything.

Sometimes you can force refresh and click the second thumbnail during page load, and the viewer will show.

**Comment by pushmatrix** [comment]
Is this still slated for 0.6?

**Comment by cdata** [comment]
Yes!

**Comment by pushmatrix** [comment]
I tested out my above example some more, and found that in Safari it throws this error:
<img width="1295" alt="Screen Shot 2019-09-18 at 2 11 25 PM" src="https://user-images.githubusercontent.com/190692/65174100-37b51880-da1e-11e9-8374-1924fb9579be.png">

This is not thrown in Chrome. However in Chrome it still doesnt show the second viewer when you try to unhid it.

Here's another barebones example of the issue: https://bedecked-profit.glitch.me
Press the *Show viewer 2* button at the bottom and you'll notice that nothing loads.

View it in Safari to see the error.
