### ISSUE TITLE
ROOM_PADDING_SCALE is unnecessary

### ISSUE THREAD

**Issue by elalish** [GoogleWebComponents/model-viewer#527]
### Description

This is just a simple code cleanup thing, but there is no need to pad the room, as the camera near plane is not set by the room's dimensions. Also, once #526 is merged, there won't even be a room anymore. Removing this will simplify things, but will also slightly change default framing, thus changing the fidelity tests.

**Comment by cdata** [comment]
Thanks a lot for filing this proactively!

**Comment by elalish** [comment]
@cdata This looks like part of #604

**Comment by elalish** [comment]
Closed via #630
