### ISSUE TITLE
HDR environment maps are not interpolated

### ISSUE THREAD

**Issue by elalish** [GoogleWebComponents/model-viewer#528]
### Description

It appears that HDR environment maps are not being interpolated in the render (looks like nearest instead of linear). 

As an aside, it also seems like our texture coordinates are accruing a lot of rounding error, because those pixels are not at all consistently sized or shaped.

#### Live Demo
https://googlewebcomponents.github.io/model-viewer/examples/lighting-and-environment.html
![Screenshot from 2019-05-03 10-45-55](https://user-images.githubusercontent.com/1649964/57155571-aad03200-6d90-11e9-89fe-1dc268437247.png)
The top uses spruit_sunrise_2k.jpg while the bottom uses spruit_sunrise_2k.hdr.

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] MacOS
- [ ] Windows

### Versions
v0.3.1

**Comment by elalish** [comment]
Perhaps this is why (second from the last comment): https://github.com/mrdoob/three.js/issues/8980

**Comment by cdata** [comment]
@mrdoob and I spent some cycles poking at this a few months back. This is definitely something we want to fix. Thanks for filing!

**Comment by elalish** [comment]
@cdata Seems like something good to fix for 0.5.
