### ISSUE TITLE
Configuration to raise interaction prompt automatically without requiring focus

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#529]
There are some scenarios where it is desirable to raise the interaction prompt automatically, without requiring that the user focus on the element first. Unfortunately, it is not possible to enable this use case by invoking `.focus()` on `<model-viewer>` because not all browsers allow focusing elements prior to user interaction.

Let's add a configuration that causes the interaction prompt to be raised automatically (after the configured `interaction-prompt-threshold`), regardless of focus state.

**Comment by pushmatrix** [comment]
Big +1 to this

**Comment by elalish** [comment]
The only case I can think of where I would not want the interaction prompt to come up is when camera-controls are not enabled or the model is not visible. Should we just change the logic to that, or do we really want an extra API to turn it on and off for the non-focused case? We don't currently allow turning the prompt off when focused (except by setting a huge threshold), so this seems consistent.

**Comment by pushmatrix** [comment]
I don't see the need for the extra API, I'd just keep it simple

**Comment by cdata** [comment]
I think that for the sake of migration, let's layer on the behavior for now. I filed https://github.com/GoogleWebComponents/model-viewer/issues/623 to cover overhauling the fundamental behavior of the interaction prompt.

Sorry this response came so late 🙇
