### ISSUE TITLE
Enable users to opt-in to Quick Look integration in iOS Chrome

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#534]
Unfortunately, iOS Chrome is more strict than iOS Safari when it comes to launching Quick Look for previewing .usdz files. iOS Safari will launch Quick Look for any .usdz file regardless of `Content-Type`. However, iOS Chrome strictly requires that the appropriate `Content-Type` be set (`model/vnd.usdz+zip`).

Worse: iOS Chrome has all of the detectable features that iOS Safari has with regards to support for launching Quick Look, so it is very difficult to infer Chrome's additional strictness.

Many users cannot change the `Content-Type` response headers sent by their servers. So, we should ensure that folks can opt-out (or opt-in) to the Quick Look integration in iOS Chrome.

https://webkit.org/blog/8421/viewing-augmented-reality-assets-in-safari-for-ios/

**Comment by streamgao** [comment]
The latest iOS chrome already supports model/vnd.usdz+zip I think?
