### ISSUE TITLE
Fidelity tests show zero matching pixels for identical images with threshold 0

### ISSUE THREAD

**Issue by elalish** [GoogleWebComponents/model-viewer#537]
### Description

Sample output for identical image comparison from npm run check-fidelity:

Comparing <model-viewer> to <model-viewer> (master)

  📏 Using threshold 0.0
  📊 Matching pixels: 0.00%
  📊 Mean color distance: 0.00%
  📊 Mean color distance (mismatching pixels only): 0.00%

  📏 Using threshold 1.0
  📊 Matching pixels: 100.00%
  📊 Mean color distance: 0.00%
  📊 Mean color distance (mismatching pixels only): 0.00%

  📏 Using threshold 10.0
  📊 Matching pixels: 100.00%
  📊 Mean color distance: 0.00%
  📊 Mean color distance (mismatching pixels only): 0.00%

The problem is that identical pixels are defined as < threshold apart, and they can't be less than zero. We could just remove the threshold 0 version, since that is actually what threshold 1 means, but I think it would probably be clearer to make identical mean <= threshold.

**Comment by cdata** [comment]
Thanks for pointing this out!
