### ISSUE TITLE
Samsung Internet has prefixed Fullscreen API and requires a polyfill

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#543]
~We have received some reports that the AR button does not work on the Samsung Galaxy S9 (that possibly extends to other Samsung devices). We should investigate what is happening to ensure compatibility with these devices.~

We should update our compatibility docs to include Samsung Internet, since it is pegged at a version of Chrome that is ~10 versions behind stable. And, we should see if we can mitigate the issue by using prefixed versions of the API if we detect them.

**Comment by Esteban26** [comment]
I'm facing the same issue with another device Huawei Mate 20 Lite, AR button is not working.

**Comment by cdata** [comment]
@Esteban26 can you share the browser (and its version) that you are using?

**Comment by Esteban26** [comment]
Sorry, for some reason my canary version was upgraded to the version 76, I removed it and used 72 again and now it is working properly, but I can confirm it is not working on Samsung devices, I checked with a Samsung S8 device with Chrome Canary 72 and when I tap the AR button the AR panel blinks and is getting hide immediately.

**Comment by Esteban26** [comment]
This is a video showing the behavior on the S8 device https://drive.google.com/file/d/1lgUNaeAUaHMTEyLaH8ZlbwBEF87s25Bw/view?usp=sharing

**Comment by cdata** [comment]
I have confirmed that the originally posted problem is that Samsung Internet browser does not have unprefixed Fullscreen API.

A mitigation for this problem is to use the Fullscreen API polyfill. You can add it to your site with the following HTML:

```html
<script src="https://unpkg.com/fullscreen-polyfill@1.0.2/dist/fullscreen.polyfill.js"></script>
```

It might be trivial for us to look for a prefixed version of the Fullscreen API and use that internally, so a future version may no longer require the polyfill if we fix this bug.

**Comment by Esteban26** [comment]
@cdata Since which version of Google Chrome are WebXR Apis enabled enabled by default to use the AR functionality? My is because today i checked with google chrome version 74.0.3729.136 and AR functionality worked without enable any flag and I checked and they are set with the default value.
 Last week I was not able to test there, only on chrome canary,  do you have knowledge about it or when they were enabled?

![Screenshot_20190513-112651](https://user-images.githubusercontent.com/1881501/57638423-5b99b680-7573-11e9-947e-78b6a8926bc3.jpg)

**Comment by johnpallett** [comment]
@Esteban26 WebXR should not be enabled by default in Chrome 74. What is the behavior you are seeing? One recent change is the availability of Scene Viewer as part of ARCore 1.9, could that be what you are seeing?

**Comment by Esteban26** [comment]
![Screenshot_20190513-110815](https://user-images.githubusercontent.com/1881501/57640269-a74e5f00-7577-11e9-9f5d-da76920e30af.jpg)
Yes, it seems to be scene viewer the page I'm seeing. So, if users have  installed ARCore version >= 1.9  , Chrome will be using ARCore -> Scene viewer tool to use AR functionality?

**Comment by johnpallett** [comment]
Correct, ARCore >= 1.9 will use Scene Viewer on Android (assuming the 'ar' attribute is enabled)

Can you clarify which documentation is confusing? I think [the AR page](https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html) is fairly clear but maybe there is somewhere else?

**Comment by Esteban26** [comment]
Yes, I already noticed you added the **ar**  attribute there, a few days ago it was not documented, but thanks a lot, one more question, is there a way to verify from code if AR is enabled? we have a custom AR button and when it is tapped we display the 3d model, but if AR is not enabled it should not be displayed in our case, is it possible?

**Comment by johnpallett** [comment]
If you mean 'can you detect whether ARCore 1.9 / Scene Viewer is installed on Android' the answer is not that we're aware of. This is why the default icon is deliberately designed to support both AR (when available) and a fullscreen fallback (when AR is not available).

**Comment by Esteban26** [comment]
Thanks Jonh
