### ISSUE TITLE
Model shifts vertical position after exiting scene viewer

### ISSUE THREAD

**Issue by yuinchien** [GoogleWebComponents/model-viewer#546]
### Description
On my pixel 2 Chrome browser, after exiting scene viewer and returned to the website, the model would shift downward from center position. 

<img width="984" alt="Screen Shot 2019-05-13 at 6 08 56 PM" src="https://user-images.githubusercontent.com/406636/57663778-3ecca580-75aa-11e9-8e5f-4ff7ae049ff2.png">

#### Live Demo
https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html
https://glitch.com/~storm-list

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: vX.X.X
- three.js: rXX

**Comment by cdata** [comment]
Confirmed, thanks for reporting!

**Comment by mrdoob** [comment]
Seem like the component is not handling resizes correctly.

I've put together a test where I'm resizing a viewer every frame:
https://model-viewer-tests.glitch.me/resize.html

The model should be visible and in the center all the time.

**Comment by mrdoob** [comment]
After further testing, horizontal resizing works as expected.
It's after vertical resizing when the component misbehave.

**Comment by mrdoob** [comment]
After further testing, horizontal resizing works as expected.
It's after vertical resizing when the component misbehave.

https://model-viewer-tests.glitch.me/resize-vertical.html

**Comment by mrdoob** [comment]
It's glitchy when resizing horizontally though.
https://model-viewer-tests.glitch.me/resize-horizontal.html

**Comment by cdata** [comment]
I think the vertical alignment issue only affects master, not the latest release (v0.3.1)

@mrdoob it's possible that the horizontal glitchiness is another issue that is exacerbated by the worst case scenario resize on every frame. We try to debounce the response to resize, so there might be a bug related to that as well.

**Comment by mrdoob** [comment]
> I think the vertical alignment issue only affects master, not the latest release (v0.3.1)

/cc @elalish

**Comment by cdata** [comment]
I just finished a `git bisect`. Looks like the first bad commit was actually the r104 upgrade https://github.com/GoogleWebComponents/model-viewer/commit/5c4e0ebd4ca78124f804201b108c2544ac578cb3 🤔

**Comment by mrdoob** [comment]
This may solve the glitchyness:
https://github.com/GoogleWebComponents/model-viewer/pull/536#discussion_r281711489

**Comment by cdata** [comment]
We do set the render target back to its original value, it's just a few lines down from there

**Comment by cdata** [comment]
@mrdoob the vertical offset is pretty mysterious to me. I traversed the scene, and everything is positioned correctly. The camera is getting updated correctly. All our stuff to set the viewport and resize the renderer is the same, and seems to be using the right values.

Do you know of anything that might have changed between r101 and r104 in `WebGLRenderer` that might be relevant?

**Comment by mrdoob** [comment]
> We do set the render target back to its original value, it's just a few lines down from there

Ah, I see.

**Comment by DavidPeicho** [comment]
The fix is actually simple, if you go to [this line](https://github.com/GoogleWebComponents/model-viewer/blob/master/src/three-components/Renderer.js#L190).

You have to had something like:
```
context.drawImage(
          this.renderer.domElement,
          0,
          this.height - height,
          widthDPR,
          heightDPR,
          0,
          0,
          widthDPR,
          heightDPR);
```

The problem comes from the fact that the renderer main framebuffer is not resized to the current viewer size for optimization purpose.

**Comment by cdata** [comment]
@DavidPeicho thanks for the feedback.

I've made a reduced reproductions of the problem that demonstrate that this new behavior was introduced in r102. Try these repros out and note that on resize, r101 works as we expect and r102 does not: [r101](http://lopsided-motion.glitch.me/three-resize/r101.html), [r102](http://lopsided-motion.glitch.me/three-resize/r101.html).

I appreciate that this may be a change that was made in the name of optimization, but [we are explicit when sizing the viewport](https://github.com/GoogleWebComponents/model-viewer/blob/6c5cd8b4c05e0b15569b0f66ac1b0dcd92588960/src/three-components/Renderer.js#L185) via Three.js' public API. Shouldn't that make a difference here?

On the other hand, the notion of the "viewport" is pretty vague according to Three.js' docs, so maybe I misunderstood what it is.

At any rate, it looks like this change took place between r101 and r102. Can you or @mrdoob point me to the PR for the relevant change?

**Comment by DavidPeicho** [comment]
@cdata For me, the problem is linked to the drawing coordinates of WebGL vs Canvas.

Canvas: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage
OpenGL / WebGL: https://learnopengl.com/Getting-started/Textures

Calling `setViewport` sets the viewport for sure, but if the framebuffer isn't at the same size of what you are drawing, you will still draw at a different place that you expected relative to the DOM element.

**Comment by mrdoob** [comment]
@DavidPeicho Thanks! I'll take a look.

**Comment by cdata** [comment]
Can either of you share the related PR where this change occurred?

**Comment by mrdoob** [comment]
We write [change logs](https://github.com/mrdoob/three.js/releases) for every release. Please, search for "viewport" in that page.

**Comment by DavidPeicho** [comment]
Yes, the problem is related to [that](Make .setViewport(), .setScissor() relative to lower-left corner. #13593 (@WestLangley)).

**Comment by cdata** [comment]
Thanks!

**Comment by mrdoob** [comment]
It's probably [this one](https://github.com/mrdoob/three.js/pull/13593). I'll test @DavidPeicho's suggestion.

**Comment by cdata** [comment]
> For me, the problem is linked to the drawing coordinates of WebGL vs Canvas.

Thanks @DavidPeicho . Now that I have had a change to read the PR it makes a lot of sense.

**Comment by yuinchien** [comment]
Team work 💯

**Comment by mrdoob** [comment]
Okay, this took quite a while to figure out but https://github.com/GoogleWebComponents/model-viewer/pull/555 fixes the glitch/flashes when resizing.

https://model-viewer-tests.glitch.me/resize.html
https://model-viewer-tests.glitch.me/resize-horizontal.html
https://model-viewer-tests.glitch.me/resize-vertical.html
