### ISSUE TITLE
How can I check if model viewer script is already loaded?

### ISSUE THREAD

**Issue by Esteban26** [GoogleWebComponents/model-viewer#561]
I'd like to check if model viewer script has been loaded, otherwise create the script to be downloaded  it, how can I do this validation?

`if (!modelViewerExists) {
  createModelViewerScript();
}

function createModelViewerScript() {
   script = document.createElement('script');
   script.src = 'model-viewer.js';
   document.getElementsByTagName('head')[0].appendChild(scriptObj.script);
}`

With some other libraries you can check if some elements exist in the window object.

**Comment by cdata** [comment]
The pre-built bundle automatically registers an HTML custom element. You can check for the existence of this element using standard DOM APIs:

```javascript
function loadModuleScript() {
  var script = document.createElement('script');
  script.type = 'module'; // Important
  script.src = './path/to/dist/model-viewer.js';
  document.head.appendChild(script);
}

function loadNoModuleScript() {
  var script = document.createElement('script');
  script.setAttribute('nomodule', ''); // Important
  script.src = './path/to/dist/model-viewer-legacy.js';
  document.head.appendChild(script);
}

var modelViewerConstructor = customElements.get('model-viewer');
var modelViewerExists = modelViewerConstructor != null;

if (!modelViewerExists) {
  loadModuleScript();
  loadNoModuleScript();
}

customElements.whenDefined('model-viewer').then(function() {
  // Model viewer is ready now
});
```

**Comment by Esteban26** [comment]
Thanks, it worked.
