### ISSUE TITLE
I can't install dependencies on windows

### ISSUE THREAD

**Issue by GeorgeDevDeakin** [GoogleWebComponents/model-viewer#562]
### Description

HI,

I was not able to npm install all the dependencies utilising your source code. I received a log stating it is missing certain type of commands in the windows terminal to install the dependencies needed on the windows machine. However, I realised that it can only be installed using apple's MacOS. 

Can it only run on a MacOS or is there a way to install the dependencies on the windows machine??????

It will only install up to a point when running it on a windows machine before it complains about missing commands

Thank you

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] Helios
- [x] IE
- [x] Safari

### OS

- [x] MacOS Latest 
- [x] Windows Latest

### Versions
<!--
Latest

**Comment by smalls** [comment]
Can you include the output of the failed command?

**Comment by cdata** [comment]
We have not tried to install it on Windows. In theory, it should be installable on Windows via WSL (Windows Subsystem for Linux). If it doesn't work, we could try to help get it to a point where you can at least install it as a dependency (although some tasks such as those related to fidelity testing might not work).

**Comment by GeorgeDevDeakin** [comment]
Hi Guys,

I have managed to get it up running. It was asking for specific file dependencies.js and model-viewer.js which was missing in the code.

However the model previews on the phone, but when I try using AR it says "Looks like there is something wrong with the object". This worked fine when I tested it straight from the demo site. But having trouble loading it locally. 

I am not sure if anyone has faced this issue.

Please Help!!!

**Comment by cdata** [comment]
Sounds like you just needed to build all of the script targets. That's a relief.

@GeorgeDevDeakin the model must be served from an SSL origin (`https`, not `http`) if you want Scene Viewer to work.

**Comment by GeorgeDevDeakin** [comment]
Hi @cdata 

I am serving it with a node server locally with an https which worked with the ThreeJS.AR that required the same thing. I assumed it will work with this. Does this mean it has to be on a live server with SSL/https???

**Comment by cdata** [comment]
Yes, this is a restriction in place for Scene Viewer. The 3D model must be served from a secure origin.

**Comment by jhflink** [comment]
@cdata Regarding loading the model from a server with SSL, is there any error one can look for in regards to this? I think I'm doing it correctly but I only get a white window with no model at all(using the Astronaut model from the example) - and no errors in the console
![model-viewer](https://user-images.githubusercontent.com/46478751/58233058-1137e700-7d76-11e9-9c76-0e9aa34b1b6f.PNG)
.

**Comment by cdata** [comment]
Are you loading the model across origins? If so, you need to make sure (for browser rendering) that the model origin sets CORS headers correctly

**Comment by jhflink** [comment]
I'm loading the model from the same server, so that should be okay I think?

**Comment by cdata** [comment]
@jhflink are you still having issues? If so, can you try to share a repro case?

**Comment by jhflink** [comment]
@cdata yes I have not yet been able to solve it, wondering if it has something to do with the server since the code is basically just a few lines as described in the readme.

`<!doctype html>
<html>		
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no,minimum-scale=1.0, maximum-scale=1.0">
		<title>Modelviewer Test</title>
		
		
		
		<script type="module"
			src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js">
		</script>

		
		<script nomodule
			src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js">
		</script>
		<style>
			body {
			width: 100%
				height: 100%;
				margin: 0;
				padding: 0;
				background-color: #000000;
			}
		</style>
	</head>

	<body>		
		<model-viewer src="assets/Astronaut.glb" alt="A 3D model of an astronaut" auto-rotate camera-controls background-color="#455A64"></model-viewer>
	</body>	
</html>`

**Comment by cdata** [comment]
@jhflink the main thing that comes to mind is that if you don't have the correct url in the `src` attribute, it will fail to load the model and only show a white screen. This will show up as a failed request (in red) in the "Network" tab of Chrome DevTools. Can you check if the request is failing?

**Comment by jhflink** [comment]
@cdata This how the network tab looks.
![network_modelviewer](https://user-images.githubusercontent.com/46478751/58605485-e0eecc00-82d2-11e9-8f62-0e91a4b1b4ef.PNG)

**Comment by cdata** [comment]
Can you share the Astronaut.glb file that you are using with us? Just a guess, but the file size looks wrong. For comparison, here is the Astronaut.glb file when I load it from our documentation site (note that it is 2.6 megabytes):

![image](https://user-images.githubusercontent.com/240083/58606790-cb858d80-8251-11e9-860e-29970843d206.png)

**Comment by jhflink** [comment]
@cdata Thanks, changing the model did the trick! I did download it from the example repository but must have been corrupted somehow, just redownloaded it and it worked.

**Comment by cdata** [comment]
Awesome, in that case I'm going to close this thread as all problems seem to be resolved :)
