### ISSUE TITLE
Astronaut is too shiny on Android devices

### ISSUE THREAD

**Issue by elalish** [GoogleWebComponents/model-viewer#565]
### Description

On Android, the Astronaut model (and presumably others) is way too shiny compared to its matte look on other platforms. 

Correct: 
![Screenshot from 2019-05-23 15-22-23](https://user-images.githubusercontent.com/1649964/58290501-d41c2680-7d6e-11e9-8c84-5b5d3881915f.png)
Incorrect: 
![Screenshot from 2019-05-23 15-23-45](https://user-images.githubusercontent.com/1649964/58290506-da120780-7d6e-11e9-9bce-878f0e5486b8.png)

### Browser Affected
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS
- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.3.1
- three.js: r104

**Comment by cdata** [comment]
Thanks for filing this!

**Comment by elalish** [comment]
Actually, this bug is the same as #528, as the reason the astronaut looks shiny is because our default generated environment map is a float texture, which android devices cannot interpolate, and thus create no mipmaps for. For a matte material, we ask for the last mipmap, but in this case that's the same as the shiniest mipmap, since there's only one. You can see the same problem with a loaded HDR environment map on Android:
![Screenshot from 2019-05-24 13-27-41](https://user-images.githubusercontent.com/1649964/58355271-a693b380-7e28-11e9-8bf2-9e234be24206.png)
Which should look more like the LDR version, especially for the matte spheres:
![Screenshot from 2019-05-24 13-28-42](https://user-images.githubusercontent.com/1649964/58355291-bd3a0a80-7e28-11e9-8766-8e72ec80ee34.png)

**Comment by pushmatrix** [comment]
@elalish I'm actually getting the inverse happening on desktop.
This is just by visiting https://googlewebcomponents.github.io/model-viewer/

![shiny](https://user-images.githubusercontent.com/190692/59401846-2c40ba00-8d6a-11e9-86ab-0ea801ff2081.gif)
