### ISSUE TITLE
Environment map generation fails on some devices

### ISSUE THREAD

**Issue by soraryu** [GoogleWebComponents/model-viewer#574]
### Description

Model looks very different on different devices. 

On an Android, Honor 7X, it looks like this:
![signal-2019-05-28-141018](https://user-images.githubusercontent.com/2693840/58491645-addff780-816f-11e9-8309-5cb7f391a2ba.jpg)

On iPhone XR:
![IMG_5890](https://user-images.githubusercontent.com/2693840/58491888-1f1faa80-8170-11e9-88db-a85b392fe952.JPG)

On Android, Xiaomi Mi 9:
![Screenshot_2019-05-28-17-41-26-090_com android chrome](https://user-images.githubusercontent.com/2693840/58491857-08795380-8170-11e9-9a6c-bdb65756c9e1.png)

The last two are pretty similar but reflections still look different (not very visible in the screenshots).

#### Live Demo
https://bramble-geranium.glitch.me/

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

Devices where this is broken:

Honor 7X (BND-L21)
Android 8.0
Chrome 74.0.3729.157

Samsung Galaxy S6 (SM-G920F)
Android 7.0
Chrome 74.0.3729.157

**Comment by cdata** [comment]
Thanks for reporting, @soraryu ! We are aware that our built-in environment map is generated incorrectly on some GPUs, but until now we didn't have a public test case for it (your first image on the Honor 7X). Previously, this issue had been reported on Samsung devices.

This issue is slightly different from the other problem you pointed out, which I think is related to #565 .

Anyway, this is definitely a bug. Thanks for reporting. Any technical details you can give us regarding the Honor 7X and the browsers you are using would be helpful!

**Comment by cdata** [comment]
CC @elalish @mrdoob

**Comment by soraryu** [comment]
Ah, I see, so it's the environment map that fails.

I made a proper glitch page here, since I in the meantime actually added an environment_image to our website (because it looked nicer than the default one and I was suspecting something like this).

https://glitch.com/edit/#!/bramble-geranium

(Note that there's another "annoyance" - if the environment image isn't accessible for whatever reason, it also renders as black. I guess it should fall back to the default one and print something in the console instead.)

**Comment by soraryu** [comment]
Found another device where default environment creation fails:
Samsung Galaxy S6, SM-G920F, all available updates
Android 7.0
Chrome 74.0.3729.157

![Screenshot_20190529_004558](https://user-images.githubusercontent.com/2693840/58517294-3039dd00-81ab-11e9-8ba3-e2ede6ad5e25.jpg)

**Comment by cdata** [comment]
Awesome, thanks for the repro case @soraryu 🙌

If it is helpful to you or anyone else encountering this issue, you can work around this problem by using your own environment lighting via the `environment-image` attribute. Also, check out https://github.com/GoogleWebComponents/model-viewer/issues/521#issuecomment-488694339 where you can download our reference IBL as an HDR image. You can use the .hdr files with `<model-viewer>` without modification, and they should have better x-device compatibility.

**Comment by soraryu** [comment]
@cdata I updated the original post with details about the Honor 7X + Galaxy S6.

**Comment by elalish** [comment]
@cdata If one of us can get a device for a repro, we should probably try to fix this as part of 0.5.

**Comment by cdata** [comment]
@elalish ack filed #616
