### ISSUE TITLE
Transparency / Cutout doesn't work when entering AR preview

### ISSUE THREAD

**Issue by soraryu** [GoogleWebComponents/model-viewer#577]
### Description

I'm not sure how the model-viewer and ARCore interact, so not sure whether this is actually an ARCore issue and not for here. Still, currently it seems that having transparent textures on objects breaks when entering AR preview (and subsequently AR view).

![61490550_2251040965157833_1703461648242573312_n](https://user-images.githubusercontent.com/2693840/58512429-5c4e6180-819d-11e9-800d-6fab311abd5b.png)
_Model-Viewer (note the circles + triangles)_

![61846010_1077598099090746_6913962461028679680_n](https://user-images.githubusercontent.com/2693840/58512433-5fe1e880-819d-11e9-85d0-6f0f9fd4d67d.png)
_AR Preview (note the black borders)_

![61433655_627678491046671_1588396991891636224_n](https://user-images.githubusercontent.com/2693840/58512441-62dcd900-819d-11e9-9b85-21d84d147c77.png)
_AR View (note the black borders)_

#### Live Demo
https://cobalt-gondola.glitch.me/

### Browser Affected
I guess all on Android, tested with Chrome

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by soraryu** [comment]
Also posted this in https://github.com/google-ar/arcore-android-sdk/issues/796

**Comment by cdata** [comment]
Thanks @soraryu . This looks like an ARCore issue, not a `<model-viewer>` issue. I'll ask for feedback on this from the Scene Viewer folks.

**Comment by soraryu** [comment]
@cdata, did you hear back from the Scene Viewer team? No one responded on the ar-core repo so far.

**Comment by cdata** [comment]
@soraryu Yah, sorry for letting this fall off the radar. This was determined to be a Scene Viewer bug, and work has been assigned to fix it.

**Comment by soraryu** [comment]
Any news about this? Or a workaround to get transparency working? I know this is not a model viewer issue but noone had reacted at all in the ARCore repo. Please poke them again...

**Comment by cdata** [comment]
Hi @soraryu I regret that this issue has been assigned but not yet fixed. I'll follow-up with the team and let you know if there is anything else I can share.

**Comment by cdata** [comment]
After circling back with the team, I understand that the issue has been fixed (the bug wasn't updated to reflect this) and you should see it when ARCore updates to v1.11.

**Comment by soraryu** [comment]
I can confirm this is fixed in v1.11. Thanks!
