### ISSUE TITLE
Rendering inconsistencies with fine detailed normals + roughness 

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#587]
### Description

I'm having an issue with the lighting on certain PBR models that have a lot of small details in the normal map. The way the details in the normal map are reflecting light seems to be off and the model comes across a bit too shiny and wet.

Below are images in various viewers. They use the same environment map from here: https://github.com/GoogleWebComponents/model-viewer/issues/521#issuecomment-488694339. 

## Model Viewer
<img width="734" alt="Screen Shot 2019-06-10 at 3 34 52 PM" src="https://user-images.githubusercontent.com/190692/59221467-542af480-8b95-11e9-8422-e58bd073b112.png">
<img width="761" alt="Screen Shot 2019-06-10 at 3 34 58 PM" src="https://user-images.githubusercontent.com/190692/59221473-568d4e80-8b95-11e9-96f2-a7e4efb726ac.png">

## Sketchfab
<img width="712" alt="Screen Shot 2019-06-10 at 3 29 51 PM" src="https://user-images.githubusercontent.com/190692/59221221-c2bb8280-8b94-11e9-9092-8f847a2b4c4e.png">
<img width="739" alt="Screen Shot 2019-06-10 at 3 29 55 PM" src="https://user-images.githubusercontent.com/190692/59221224-c3ecaf80-8b94-11e9-84a4-b1d4248b27ad.png">

## Substance
<img width="754" alt="Screen Shot 2019-06-10 at 3 31 37 PM" src="https://user-images.githubusercontent.com/190692/59221268-d9fa7000-8b94-11e9-845e-ca87276ea0a6.png">

## AR Quick Look
(Doesn't use the same environment map)
<img width="504" alt="arql" src="https://user-images.githubusercontent.com/190692/59221277-debf2400-8b94-11e9-874d-738d8cfbda8d.png">

We created the material in substance painter, and Sketchfab & AR Quick Look render it as designed. Model-viewer makes it look like the normal map roughness is really low and reflective.

#### Live Demo
https://ninth-paste.glitch.me/

Download the model [here](https://github.com/GoogleWebComponents/model-viewer/files/3273539/fabricball.zip)

### Browser Affected

- [x] Chrome (74.0.3729.157)
- [x] Firefox (66.0.5)
- [x] Safari (12.0.3)

### OS

- [ ] Android (not tested)
- [x] iOS (12.3.1)
- [x] MacOS (10.14.3)

### Versions
- model-viewer: v0.3.1 and latest master #f5b3b55  
- three.js: 105

**Comment by cdata** [comment]
Thanks for reporting this @pushmatrix ! We'll take a look

**Comment by pushmatrix** [comment]
FYI: I updated the example given that shows the difference even more.

**Comment by elalish** [comment]
Okay, so looking at your metallic-roughness map, it looks like you're going for metal = 0 uniformly and roughness a bit noisy, between about 130-155? Inspecting threejs I'm seeing the metalnessMap and roughness map getting the same texture, and maybe some other issues. We might need to check out our gltf loader. I notice you have some indirection here, where scene.gltf encapsulates fabricball.glb; does this still repro if everything is baked into a single gltf?

**Comment by pushmatrix** [comment]
Yep that's what we're going for. Same thing happens with it baked into one.
Here's the gltf

[fabricball.gltf.zip](https://github.com/GoogleWebComponents/model-viewer/files/3273850/fabricball.gltf.zip)


Not sure how the indirection happened. It was originally a .glb from substance then I exported the .gltf + textures from Sketchfab.

**Comment by pushmatrix** [comment]
But yes you're right it does look like it has metalness applied to it.

**Comment by pushmatrix** [comment]
Playing around with setting the metalness map in Sketchfab to be the same as the roughness, and the model didn't look the same as model viewer:

<img width="991" alt="Screen Shot 2019-06-10 at 5 42 08 PM" src="https://user-images.githubusercontent.com/190692/59228940-1931bc80-8ba7-11e9-981e-6f3fcd3ab8e5.png">

However setting the roughness multiplier to 0.5 and then it looked pretty similar to model-viewer:
<img width="1014" alt="Screen Shot 2019-06-10 at 5 38 28 PM" src="https://user-images.githubusercontent.com/190692/59228749-9f99ce80-8ba6-11e9-891b-6e974ab21de3.png">

**Comment by pushmatrix** [comment]
Filament does seem a bit less shiny:

<img width="744" alt="Screen Shot 2019-06-12 at 11 43 49 AM" src="https://user-images.githubusercontent.com/190692/59366276-169aa880-8d08-11e9-9abc-546217faf618.png">

**Comment by pushmatrix** [comment]
@elalish Is the rendering issue here solved by #591 or did #591 just make it so PMREM is on by default? When this issue was first posted I had mistakenly not turned on PMREM, but then updated the issue to show the fabric ball being way too shiny even with PMREM on.

Does #591 make it less shiny?

**Comment by elalish** [comment]
No, but I’m also working on that. That’s a bigger change affecting the
internals of three js materials and shaders.

**Comment by pushmatrix** [comment]
Is it ok if we reopen this issue then?

**Comment by cdata** [comment]
Sorry about letting this get caught in the issue-closing crossfire @pushmatrix
