### ISSUE TITLE
Camera-orbit theta value rotates beyond 360 degrees

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#590]
### Description

When you rotate the model a lot in one direction, the theta goes over 360 degrees instead of wrapping back around. When setting the camera orbit theta back to 0deg, then the model overspins.

See here: https://nickel-longship.glitch.me/

This makes it hard to reset the camera back to the original position.

### Browser Affected
All browsers

### OS
All OS
### Versions
- model-viewer: 0.3.1
- three.js: r101

**Comment by cdata** [comment]
Sounds good! We might be able to implement this by wrapping theta at 360 degrees. We should probably also fix interpolation so that it always moves across the shortest arc to the destination accounting for wrapping.

**Comment by pushmatrix** [comment]
@elalish try the demo here: https://nickel-longship.glitch.me/
