### ISSUE TITLE
Screenshot API: Ability to export render as a data URL

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#596]
There's many cases where it'd be useful to export an image of the model-viewer. Either to download it, or to access and manipulate it with javascript.

Normally I'd use `canvas.toDataURL()`, but since we don't have access to the canvas element in the Shadow DOM, it'd be great to have something like `modelviewer.toDataURL()`

**Comment by cdata** [comment]
`toDataURL` seems like an uncontroversial API to add. Do we need to cover any other cases, like getting access to raw bitmap data?

**Comment by pushmatrix** [comment]
I suppose `.getImageData(left, top, width, height).data;` could be handy for cases where you want to crop. Most likely for when model viewer is used for taking photos of 3D products. 

I'd just start with toDataURL as it will cover a lot of cases, and if need be we can support getImageData. Would be nice to stay consistent with canvas/context.
