### ISSUE TITLE
API call for entering AR

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#597]
I can see cases where some people would want to customize their own AR badge (ex: the word 3D, or a different glyph). We could add a slot, but I could see some "enter AR buttons" being outside the viewer (ex: Having the text "Click here to view in AR" underneath the viewer).

It would be handy to have the following:

- Slot for putting in a custom badge

- `modelviewer.enterAR()`: Triggers the AR view, whether its scene viewer, arql or webxr.

- `modelviewer.supportsAR()`: Returns whether the device supports one of the AR experiences provided by model viewer.

**Comment by cdata** [comment]
We may or may not have an undocumented public method for the first one 😅 

https://github.com/GoogleWebComponents/model-viewer/blob/846d3855a96e30bddac71d52c119548a63b69255/src/features/ar.ts#L151-L175

Does that look suitable for `enterAR`?

The tricky thing with `supportsAR` is that in some cases the check is difficult or impossible. The problematic scenarios right now include:

 - On iOS Chrome, the check requires that we make a `HEAD` request to the server hosting the `.usdz` file to make sure it is sending the correct `Content-Type`. A future version of iOS Chrome will probably make this easier, but right now it kinda sucks.
 - For Scene Viewer on Android, the check requires that we trigger the intent and hope that the browser correctly observes the specified fallback URL (not all Android browsers respect this, although the ones that don't are somewhat fringe). The tricky thing is that the intent usually doesn't work unless it is triggered in response to user interaction.

**Comment by pushmatrix** [comment]
Ah yes, `activateAR` is great! Is it just a matter of documenting that?

As for `supportsAR`, I can see how it's difficult to detect if they have actual AR support. The use case I was thinking of was more for whether it supports Quick Look or Sceneviewer at all (even if they don't support the AR tab / view in your space). So maybe `supportsAR` is a bad name, but I don't know what else to call it. The "Object" tab in ARQL and the fullscreen view in sceneview is somewhat of . a redundant state that I don't know what the name of that should be.

Essentially looking for a way to hide the badge and replace it with our own, except use the same logic model-viewer uses to determine whether a badge should be displayed or not.

**Comment by cdata** [comment]
Yeah, I think it would just be a matter of adding documentation.

Currently, if you customize the AR button by using `slot="ar-button"`, the custom buttons you put there will only be displayed when the default AR button would display, so you would not need to re-implement that logic.

For `supportsAR`, it would be easier for us to just report whether or not we would display the AR button. But, `supportsAR` would be misleading language in that case. Maybe `isARCandidate` or something like that would be better. WDYT?

**Comment by pushmatrix** [comment]
Yeah `isARCandidate` sounds pretty good.

One thing we are running into with customizing the AR button via slot is that there's a bit of a flicker as it switches from the default to our own. That's because we insert the ar-button slot via javascript. Our model-viewer tag gets generated for us and we can't put stuff inside the html that the server returns.

So because the ar-button displays immediately on the badge (even before the model is loaded), you see the old button until the javascript runs to pop in the new one. Any thoughts on how to get around that?

**Comment by cdata** [comment]
> we can't put stuff inside the html that the server returns

Can you elaborate on that a little bit? What are the constraints here?

**Comment by cdata** [comment]
@pushmatrix is there anything actionable here? LMK if you think we can close it out, otherwise let's update it.

**Comment by pushmatrix** [comment]
I'd say this can be closed.
