### ISSUE TITLE
Figure out our post-processing story

### ISSUE THREAD

**Issue by smalls** [GoogleWebComponents/model-viewer#6]
Perhaps create these as optional addons? Would `vignette` fit into that category?

**Comment by cdata** [comment]
@jsantell and I did a fairly comprehensive review of near-term rendering topics including post-processing, and filed issues to cover most of the work. I'm going to close this issue for now so that we can rely on the other ones we have since written.

**Comment by cdata** [comment]
For future reference, the newer issues that cover this topic are #213 #212 #211 and #210
