### ISSUE TITLE
LDR environment maps without PMREM do not light nonmetallic, rough objects at all.

### ISSUE THREAD

**Issue by elalish** [GoogleWebComponents/model-viewer#601]
### Description

All of our lighting for objects like this (metal = 0, roughness = 1 is the default for unspecified materials, like the Astronaut) comes from our stage light; the environment is completely ignored for jpgs. It has very little effect on shiny objects (they are still much too dark), but with metal = 1, everything is fine.

#### Live Demo
The duck, when the stage light turns off: https://googlewebcomponents.github.io/model-viewer/examples/lighting-and-environment.html
![Screenshot from 2019-06-04 11-11-30](https://user-images.githubusercontent.com/1649964/58903147-87631480-86b9-11e9-9e7f-ce03fdfede52.png)

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [x] Linux
- [ ] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.3.1
- three.js: r104

**Comment by cdata** [comment]
@mrdoob I remember talking to you about something like this at some point. Do you have any thoughts on this?
