### ISSUE TITLE
Deprecate / remove align-model attribute

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#603]
In #441 , we introduced the `align-model` attribute as an escape-hatch for users who want to stage their models in a special way and did not want to use the default staging.

Once we implement #453 , `align-model` won't be as useful, and the escape hatch use case will mostly be covered by `camera-target`. At that point, we should deprecate and remove `align-model`.

**Comment by elalish** [comment]
This should also fix #271.

**Comment by elalish** [comment]
We should also think about this in the context of #426.

**Comment by cdata** [comment]
> This should also fix #271.

I don't know if this is correct, because we do some work to reset the model's transform when placing in AR and it might side-step the `align-model` offset entirely.

**Comment by cdata** [comment]
Let's deprecate in v0.7.0 when we introduce camera-target and remove completely in v1.0.0

**Comment by elalish** [comment]
deprecated on 0.6, removal now slated for 0.7.
