### ISSUE TITLE
Interaction prompt should not require focus

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#623]
Upon finishing #529 , we will have made it possible for the interaction prompt to surface automatically without requiring focus. @elalish [pointed out](https://github.com/GoogleWebComponents/model-viewer/issues/529#issuecomment-500580856) that this might be the most desirable default in all cases.

Let's overhaul interaction prompt behavior so that the interaction prompt is raised without requiring focus or related complex internal state management.

**Comment by cdata** [comment]
As part of this change, we will remove the `interaction-prompt` attribute

**Comment by soraryu** [comment]
If you remove the interaction-prompt attribute, will it still be possible to turn the prompt off? I can come up with quite some use cases where I wouldn't want that on my models.

1) a 3d object that is controlled by script, e.g. as background element of a webpage, and not interactable by default (there might be text over it)
2) something that it's part of the design of a webpage (see login page of sketchfab.com with their little robot guy - the interaction prompt would most likely not fit into that design)

**Comment by cdata** [comment]
@soraryu there will be no change to your options for turning it off completely, because AFAIK we don't have an explicit way to do that yet :) maybe we should have one?

Currently, these are the ways I can think of to indirectly disable the prompt:

 1. Replace the prompt with an empty element (e.g., `<div slot="interaction-prompt"></div>`)
     - Note: this only turns off the "visual" prompt, screen readers will still read a prompt
 2. Change `interaction-prompt-threshold` to some really, really big number
 3. Set `interaction-prompt="when-focused" and then never allow `<model-viewer>` to be focused

If you are interested in turning off the prompt completely, would you be willing to file an issue to request that feature?
