### ISSUE TITLE
Moiré effect on certain materials

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#632]
### Description

On one of the models we've tested, we've seen a pretty noticeable moire effect.

<img width="538" alt="Screen Shot 2019-06-12 at 10 14 11 AM" src="https://user-images.githubusercontent.com/190692/59358612-e3055180-8cfa-11e9-875e-7e8261e63a88.png">

<img width="525" alt="Screen Shot 2019-06-12 at 10 14 15 AM" src="https://user-images.githubusercontent.com/190692/59358625-e7316f00-8cfa-11e9-91db-5bfccac0565b.png">

I have a live demo of it here:
https://seed-oatmeal.glitch.me/

I know this isn't a model-viewer issue, and more something in Three, but I'm wondering if there's anything we can do to soften out this effect.

I feel like some of the reflectiveness there is due to https://github.com/GoogleWebComponents/model-viewer/issues/587, but even with that fix the effect would likely persist.

For reference, this is what we're expecting it to look like out of Substance:

<img width="638" alt="Screen Shot 2019-06-12 at 10 19 43 AM" src="https://user-images.githubusercontent.com/190692/59359051-a9811600-8cfb-11e9-8c3d-9b7d0f56a685.png">

<img width="1024" alt="Screen Shot 2019-06-12 at 10 19 49 AM" src="https://user-images.githubusercontent.com/190692/59359060-abe37000-8cfb-11e9-81f9-7c3dae14cc62.png">

**Comment by cdata** [comment]
Thanks for sharing this example render with us. I think it illustrates the problem very clearly. I've added this bug to our meta bug capturing our current set of rendering issues to be completed by v0.6.0 release (https://github.com/GoogleWebComponents/model-viewer/issues/616).
