### ISSUE TITLE
Extreme lagginess / jerky movement in desktop Safari

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#634]
### Description
On my 15" retina mbp in Safari, when I view a model-viewer that takes up a lot of the screen, the movement is suddenly very laggy and the model jerks around.

![janky](https://user-images.githubusercontent.com/190692/59398191-4d4ede00-8d5d-11e9-8c8f-1cd26eb6d012.gif)

It gets smoother the smaller the viewport is.

Repro:
- Safari 12.1.1 (14607.2.6.11)
- Visit https://googlewebcomponents.github.io/model-viewer/
- Make the window as big as possible
- Try rotating the astronaut

It is even more noticeable if you are in the scaled display: 

<img width="370" alt="Screen Shot 2019-06-12 at 9 55 43 PM" src="https://user-images.githubusercontent.com/190692/59398797-86884d80-8d5f-11e9-9ce9-f03e48d8cd78.png">

I have noticed performance on iOS is not as good as on Android. My XS Max is somewhat choppy when I rotate models, but on a pixel 2 it's buttery smooth.

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS (10.14.5)
- [ ] Windows

<img width="331" alt="Screen Shot 2019-06-12 at 11 07 40 PM" src="https://user-images.githubusercontent.com/190692/59400887-ea624480-8d66-11e9-98ff-15380a5da5f4.png">

### Versions
- model-viewer: v0.3.1
- three.js: r104

**Comment by cdata** [comment]
Tracking two separate issues here:

 1. Safari is slower than other browsers
 2. At some recent point in history, we introduced crazy jank to our controls

I ran a `git-bisect` and it appears the jank (2) was introduced in https://github.com/GoogleWebComponents/model-viewer/pull/563

FYI @elalish we may need to revert the configurable FOV change if we cannot land a fix early tomorrow.

**Comment by cdata** [comment]
I think the issue is due to incorrect compensation for long-running frames. In Chrome, frames always stay in budget, but in Safari I'm seeing the delta between frames flap rapidly between positive and negative across frames.
