### ISSUE TITLE
Require 'src' attribute

### ISSUE THREAD

**Issue by jsantell** [GoogleWebComponents/model-viewer#64]
For inline, WebXR, and Magic Leap, we'll need a glTF/glb file. There's a scenario where only the USDZ is provided, with a poster, which is more or less no different from iOS's native AR Quick Look. 

This may already work due to the mixin pattern, but something we should confirm, and/or clarify in docs.

**Comment by cdata** [comment]
This has been clarified in docs and is the current behavior of the element, so I'm going to close off this issue.
