### ISSUE TITLE
Camera control not working with touch gestures on Android

### ISSUE THREAD

**Issue by vortice3D** [GoogleWebComponents/model-viewer#640]
### Description

Camera control works great when using this component from a desktop computer (both mouse or touch-screen) but is not responding to touch gestures on Android. 

#### Live Demo

Testable directly on the model-viewer component examples.

### Browser Affected
Chrome

### OS
Android

### Devices
Motorola Moto G6
Samsung Galaxy Tab S4

**Comment by pushmatrix** [comment]
Just to be sure, are you tapping on the viewer first to gain focus?

**Comment by cdata** [comment]
Thanks for reporting @vortice3D . I cannot reproduce this issue. Please provide a test case!

**Comment by vortice3D** [comment]
Hi **Daniel** and **Christoper**:

Well, after re-testing the examples, if I double-touch on the canvas' container I can have the "astronaut" responding correctly to my touch gestures, in both devices.

My fault. I apologize for the inconveniences.

Best regards.

**Comment by cdata** [comment]
@vortice3D btw please track #479 and #500 for future improvements in this area.
