### ISSUE TITLE
Use consistent, cross-device compatible single rendering path for IBL

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#647]
As of this writing, our IBL implementation choices lead to results that range from from undesirable (#565) to totally broken (#574) in some configurations on some devices.

Our generated IBL currently depends on the [HalfFloat WebGL extension](https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_half_float), but this extension is inconsistently available leading to inconsistent lighting across devices.

Furthermore, IBL results in Three.js can vary significantly depending on the rendering path we use (PMREM/HDR vs non-PMREM/LDR, see #601).

In order to address these inconsistencies, achieve more consistent rendering across devices and simplify the mental model for our users, the following improvements are proposed:

 - The default rendering path will apply PMREM (a breaking change)
 - The `experimental-pmrem` attribute will be removed
 - The generated IBL will use RGBE encoding, aligning to what we use for external HDR IBLs
 - A gaussian blur pass will be implemented to achieve visual parity between generated and reference IBL

**Comment by elalish** [comment]
Closed via #591
