### ISSUE TITLE
Quality Tests link is broken or down

### ISSUE THREAD

**Issue by donmccurdy** [GoogleWebComponents/model-viewer#655]
Visiting https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html, I see the message `Loading...` and the console shows a 404 for `config.json`.

**Comment by cdata** [comment]
Looks like we accidentally stopped publishing them to gh-pages at some point...

**Comment by donmccurdy** [comment]
Appears to be broken again. 🙃

**Comment by cdata** [comment]
Yah, looks like our CI is having a day. I'm diagnosing the issue now. Thanks for the heads up 👍

**Comment by cdata** [comment]
This is fixed again as of https://github.com/GoogleWebComponents/model-viewer/commit/42ae83213eceb70185390b0c1c866ff9b318ec68
