### ISSUE TITLE
AR Quick View button won't show up on iOS Chrome

### ISSUE THREAD

**Issue by AbhishekKumarTank** [GoogleWebComponents/model-viewer#669]
### Browser Affected
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

Hi,

I know that the new AR Quick View feature where you can load AR animals from google search works on iOS Google Chrome. However when we use <model-viewer> in our app we do not see the quick view button on iOS Google Chrome. We are using fullscreen polyfill. Are we missing something or is there any hack to load AR Quick View button on iOS Chrome?

regards
Abhishek

**Comment by alangdm** [comment]
Are you setting `quick-look-browsers` to `"safari chrome"`?
If not, you probably should, since v0.4 chrome is not included by default
https://github.com/GoogleWebComponents/model-viewer/releases/tag/v0.4.0

**Comment by AbhishekKumarTank** [comment]
Hi @alangdm 
Thanks for the reply. I tried setting quick-look-browsers to "safari chrome". The quick look button starts to show up, however when I tap on the button instead of launching the Quick view it start to download the model.
Below is the code for your reference. What am I missing here?

`<model-viewer src="https://cdn.glitch.com/14f45603-5438-4559-8da2-3750473d630a%2Fscene.glb?v=1561489204787"
                  alt="Sample Model"
                  background-color="#70BCD1"
                  shadow-intensity="1"
                  camera-controls
                  interaction-prompt="auto"
                  auto-rotate
                  quick-look-browsers="safari chrome"
                  ios-src="https://cdn.glitch.com/14f45603-5438-4559-8da2-3750473d630a%2Fscene.usdz?v=1561501106455"
                  ar magic-leap>`

**Comment by AbhishekKumarTank** [comment]
As per the post [here](https://github.com/GoogleWebComponents/model-viewer/pull/626), we need to set Content-Type header for .usdz to model/vnd.usdz+zip for it to work correctly.

This works fine after these changes.

**Comment by soraryu** [comment]
@alangdm note that this is not documented yet in https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html, I suggest adding the quick-look-browsers property there.
