### ISSUE TITLE
Ar not working correctly

### ISSUE THREAD

**Issue by OriginLive** [GoogleWebComponents/model-viewer#681]
### Description

Using 
<script type="module"
    src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js">
</script>
Does not provide my phone with  "View in your space". I only see the object and can rotate it.

The example below works on my phone however:
https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html

#### Live Demo

can provide exported scene.glb from threejs

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
    src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js">

**Comment by notleigh** [comment]
I haven't found documentation on this, but my testing points to AR only being available when the page is served https.  Is your sample running on a https-enabled server?

Running the same page on a http server on my local network I see the behaviour you're describing, but uploading that to an external server with https I receive the "View in your space" prompt.

**Comment by OriginLive** [comment]
After setting up https, and updating the certs, it worked perfectly.
Many thanks!
