### ISSUE TITLE
How is the size/scale of a glTF defined?

### ISSUE THREAD

**Issue by PawelGIX** [GoogleWebComponents/model-viewer#688]
### Description
How is the scale of the model defined in the gltf files defined?
In the AR view, it displays the size of the bus.
How to change it? Is there documentation for this tamat?
Example:
https://dyfuzjastudio.com/ar/vw_toster_android/

#### Live Demo

https://dyfuzjastudio.com/ar/vw_toster_android/

### Browser Affected

- [ x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.5.0/master
- three.js: rXX

**Comment by cdata** [comment]
Hi @PawelGIX , [we have a short blurb on this in our README](https://github.com/GoogleWebComponents/model-viewer#augmented-reality). The gist of it is that if a cube in your model is 1 x 1 x 1 unit big, it will be 1m x 1m x 1m in AR. If the model is too big, right now the best option is to edit it in a design tool (like [Blender](https://www.blender.org/)).
