### ISSUE TITLE
Problems displaying model in AR

### ISSUE THREAD

**Issue by arturomarruffo** [GoogleWebComponents/model-viewer#692]
The GLB file is being displayed correctly on the website, but it suddenly stopped working in AR mode.

https://www.nextlatam.com/modelviewer/sodimac_demo.html

- [x] Chrome
- [x] Android
- model-viewer: v0.5.0

**Comment by cdata** [comment]
Hey, thanks for reporting! It does indeed seem like there is an issue. I'm looking into it.

**Comment by cdata** [comment]
Closing this one as a dupe of #693
