### ISSUE TITLE
Glitches on going back and forth between SceneViewer and model-viewer

### ISSUE THREAD

**Issue by soraryu** [GoogleWebComponents/model-viewer#701]
### Description
As outlined [here](https://github.com/GoogleWebComponents/model-viewer/issues/693#issuecomment-519237456), I have some issues with SceneViewer launching from model-viewer and glitches around that.
First launch after website reload usually works, but subsequent clicks on the "go to scene viewer" button _sometimes_ do weird things. 

Glitches are different - I have seen:
- SceneViewer showing "looks like there's something wrong with this object" on objects that were launching just fine a second ago
![IMG_20190808_095427](https://user-images.githubusercontent.com/2693840/62685200-7c32aa80-b9c2-11e9-85e4-49dd30ee64cf.jpg)

- SceneViewer loading on a black background instead of white and quickly quitting / going back to webpage
(wasn't able to take a screenshot of this, most of the times it's just for a few frames, sometimes it's stuck on black)

- SceneViewer AR Mode getting no camera image, after switching to regular camera it worked again ([link to video of the behaviour](https://www.youtube.com/watch?v=dgmHW7kw12Q))
![Screenshot_20190808-094439_Google](https://user-images.githubusercontent.com/2693840/62685101-4392d100-b9c2-11e9-8d4d-dcf793512687.jpg)

- SceneViewer loading screen alternating between black and white background every frame ([link to video of the behaviour](https://youtu.be/hlzUhN6egco))

- canvasses showing the background color + AR button after going back from scene viewer (wasn't able to take a screenshot but I think this is #619 anyways)

- some canvasses completely blank after going back from scene viewer
![Screenshot_2019-08-08-08-53-11-971_com android chrome](https://user-images.githubusercontent.com/2693840/62685734-8608dd80-b9c3-11e9-8bcf-004cf9f5b636.png)

#### Live Demo
https://near-singularity.glitch.me/

Only way to reproduce that I know of is to repeatedly click that button, go to AR view, go back, click the button on the same model or the second model, repeat until something glitches, but ultimately it will glitch. It seems to glitch faster/more often on Xiaomi Mi 9 and less often (but still ultimately) on Samsung Galaxy S9+.

Also, the issue seems to get worse after switching away from Chrome and coming back at a later point on both devices when not reloading the webpage (memory related?), but that could just be a feeling.

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.5.1
- Device: Xiaomi Mi 9 and Samsung Galaxy S9+

**Comment by cdata** [comment]
Just noting per conversation in #693 that I believe that these issues will be fixed in #619
