### ISSUE TITLE
Animate model along with interaction prompt

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#708]
A better interaction prompt would be to move the model along with the prompt hand indicator.
This way it's clearer that the object is not just a photo.

![loop](https://user-images.githubusercontent.com/190692/63053249-579d6d80-beaf-11e9-9816-2e5a2366522b.gif)

We can fine tune the easing & speed of it, but the general idea is something like the above.

As soon as you interact with the model, the hand would disappear and the object would stop rocking back and forth.

**Comment by pushmatrix** [comment]
I might be able to find time to make a PR on it, but would like some guidance into what files something like this should live in. Also, what do you think would be the best approach for keeping the hand css in sync with the model's theta value. Seems like there could be some framerate issues animating both a webgl model and a DOM element each frame.

**Comment by pushmatrix** [comment]
Not sure how this would work with the auto-rotate feature though

**Comment by elalish** [comment]
I think the most straight-forward thing is to simply superimpose the motions of this prompt and auto-rotate, which would happen naturally, since this prompt would act on the camera while auto-rotate acts on the stage. Also, from a UX perspective, I wonder if it wouldn't be nicer to make this prompt intermittent: every few seconds, the hand appears, the model wiggles once, then stops.

**Comment by elalish** [comment]
I'd really like to see this, because it would have a secondary benefit of replacing our animated SVG, which has terrible energy cost! Chrome is much more efficient at CSS transforms.

**Comment by pushmatrix** [comment]
Yeah I agree with you on wiggling once and stopping for a bit. 

Not quite the same idea, but here's something we played around with a few months back:
![rotate](https://user-images.githubusercontent.com/190692/65075373-cd8c6d00-d964-11e9-8f13-5648198e5fcc.gif)

**Comment by elalish** [comment]
That's nice, though I might prefer a longer delay. As for where this code should live, I would say controls.ts seems like the best candidate, since that's where all the interaction prompt logic is, and it has easy access to SmoothControls. As for CSS coordination, I'll defer to @cdata.
