### ISSUE TITLE
Textures are blurring when in the distance in 0.6.0

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#724]
### Description

0.6.0 added improvements to fix issues like the Moiré issue:  https://github.com/GoogleWebComponents/model-viewer/issues/632

It does a pretty good job:
<img width="1058" alt="Screen Shot 2019-08-27 at 1 39 45 PM" src="https://user-images.githubusercontent.com/190692/63794874-d1325400-c8d0-11e9-8c96-11fa3c750bf2.png">

However on the left hand photo above, you notice some banding happening.

Looking at it closer, it looks as though the texture is blurring the further away from the camera it is. Seems like anisotropic filtering issue.
<img width="1244" alt="Screen Shot 2019-08-27 at 1 40 14 PM" src="https://user-images.githubusercontent.com/190692/63794924-f1621300-c8d0-11e9-8a96-d0c76682298e.png">

Here's a gif of it happening (notice the detail in the stitching and zippers)
![details](https://user-images.githubusercontent.com/190692/63795508-1014d980-c8d2-11e9-92f2-3efd3258580b.gif)

#### Live Demo
Compare both new and old viewers here: https://saber-soup.glitch.me/

### Browser Affected

- [ x ] Chrome 76.0.3809.100
- [ x ] Safari (desktop and mobile)  12.1.1 (14607.2.6.1.1)

### OS

- [x ] iOS (12.3)
- [x ] MacOS (10.14.5)

### Versions

- model-viewer: v0.6.0
- three.js: r105

**Comment by pushmatrix** [comment]
@elalish I see you have a PR up. If it helps with testing, try the fabricball glb:
https://cdn.glitch.com/da3e3c43-6b19-47cf-88d3-58c2cab4f291%2F64ad5c74-536a-487f-a10b-8f52b0e89317_fabricball.glb?v=1568827109696

You can see the mip artifacts really well with that one:
<img width="617" alt="Screen Shot 2019-09-18 at 1 35 57 PM" src="https://user-images.githubusercontent.com/190692/65171625-48af5b00-da19-11e9-9461-2dea330b4649.png">

<img width="585" alt="Screen Shot 2019-09-18 at 1 36 34 PM" src="https://user-images.githubusercontent.com/190692/65171643-57960d80-da19-11e9-8ae1-9fd1f13e0094.png">

**Comment by pushmatrix** [comment]
This is not fixed: https://github.com/GoogleWebComponents/model-viewer/pull/750#issuecomment-539492253

**Comment by cdata** [comment]
Sorry about that @pushmatrix this shouldn't have been closed off yet.

**Comment by elalish** [comment]
@pushmatrix Okay, so this'll be a little tricky because there are a bunch of separate issues conflated in this bug. The fabric ball error is a side effect of the quick fix I did to get rid of the moire shown in 0.3 above. I'm working on solving that in a better way. However, the detail banding you're seeing on 0.6 I believe I just found the cause of. It's actually in your bag.glb! When I converted it to glTF it includes this: ```
"samplers": [
    {
      "magFilter": 9729,
      "minFilter": 9985,
      "wrapS": 10497,
      "wrapT": 10497
    }
  ],
```
That corresponds to a minFilter of LinearMipmapNearest, when to get rid of the banding we need LinearMipmapLinear (which is our default, so omitting it will also suffice). I'd love to understand what authoring tool put that in there and why!

**Comment by pushmatrix** [comment]
@elalish Very interesting....

Substance Painter is what we used to export it.

**Comment by pushmatrix** [comment]
Would you like me to email them and ask why they do that?

**Comment by elalish** [comment]
@pushmatrix Yes, definitely. If the person using that program didn't specify it explicitly, then I'm pretty sure it's a bug.

**Comment by elalish** [comment]
If you ever want to check a particular model, I use the SpectorJS Chrome plugin. It may look daunting, but if you click on MeshStandardMaterial, you can scroll down in the side pane to see all the textures associated with the object and their settings. That's where I first noticed LINEAR_MIPMAP_NEAREST.
![image](https://user-images.githubusercontent.com/1649964/66431422-d1923480-e9d0-11e9-912c-f87993e3ee71.png)

**Comment by elalish** [comment]
@pushmatrix One other thing I noticed with that bag model: The shadow plane is much larger than it needs to be and ends up dominating the bounding box calculation, which results in the model being pretty zoomed out by default. You may want to pay some attention to that in your export pipeline as well.
![image](https://user-images.githubusercontent.com/1649964/66431881-bc69d580-e9d1-11e9-95ca-89ec59349d87.png)

**Comment by pushmatrix** [comment]
@elalish That's a good tip on Specter.

Re: Bag shadow, that's back when we were doing shadow planes. We aren't anymore.
Some viewers we used in the past had support for not using the shadow plane as part of the bounding box calc, which was handy.

**Comment by pushmatrix** [comment]
@elalish 
Hmm seems to still be happening even without those mip settings:
<img width="409" alt="Screen Shot 2019-10-10 at 4 54 43 PM" src="https://user-images.githubusercontent.com/190692/66605836-ced54200-eb7e-11e9-9c2c-124703d5c7c9.png">

https://pacific-repair.glitch.me/

**Comment by elalish** [comment]
Hmm, I think we need to be more specific about what "it" is. To me the issue I was referring to appears fixed, as compared to this:
![image](https://user-images.githubusercontent.com/1649964/66610508-93cc1200-eb70-11e9-9e22-738dabf4c2e1.png)

**Comment by pushmatrix** [comment]
@elalish I guess this issue ended up being two separate things. What you pointed out above is indeed fix, but the original banding is still present:
<img width="291" alt="Screen Shot 2019-10-10 at 8 06 25 PM" src="https://user-images.githubusercontent.com/190692/66615206-bc1c3680-eb99-11e9-9863-94274c90501b.png">


Compared to Don's viewer:
<img width="1140" alt="Screen Shot 2019-10-10 at 8 07 30 PM" src="https://user-images.githubusercontent.com/190692/66615209-be7e9080-eb99-11e9-83ca-f0821fd3df6b.png">

**Comment by elalish** [comment]
Actually, I do see the same thing in Don's viewer, just from a larger distance: 
![image](https://user-images.githubusercontent.com/1649964/66667491-fa503f00-ec07-11e9-98b1-8c63f6f62afd.png)
It looks like those lines are actually triangle edges, but i'm not sure what's making them visible. Might be good to take a close look in the editing tool and see if that turns anything up. Maybe something about the interpolation of vertex normals?

**Comment by pushmatrix** [comment]
Very interesting. Thanks for digging into that. We will take a look to see if anything fishy is on our end. Maybe substance is doing something strange again with the export

**Comment by pushmatrix** [comment]
@elalish I remember you saying that one of the drawbacks of this fix is that it introduced a loss of detail. 

I can confirm that with one of our products, where it used to look like:

<img width="369" alt="Screen Shot 2019-10-23 at 10 25 34 AM" src="https://user-images.githubusercontent.com/190692/67403309-b94d1880-f57f-11e9-9dfd-5f28fee3a889.png">

And now looks like this at the same distance:

<img width="239" alt="Screen Shot 2019-10-23 at 10 25 38 AM" src="https://user-images.githubusercontent.com/190692/67403328-c10cbd00-f57f-11e9-9fb7-884f38797140.png">

Lost all the details in the leather.

**Comment by NEONFIVE** [comment]
normalmap details are blurred since v0.6, also in v0.7.1.
Compared v0.5 with v0.7.1, i think it's just the normalmap - any albedo, ORM textures are looking fine and similar in both versions. 
please take a look to the image: 

![modelviewer_normalmaps](https://user-images.githubusercontent.com/56956825/67470071-7bb6c100-f64d-11e9-9184-4ebf8bf664cd.jpg)

**Comment by elalish** [comment]
@NEONFIVE Yes, this is a known issue, as stated above. Really it was a hack to reduce aliasing. I'm currently working on a better fix so that the normal maps can go back to full resolution.

**Comment by elalish** [comment]
@pushmatrix Could you give me a more recent version of your bag model (or any others that demonstrate these problems)? I know you've done some work on it, and it would also be great if I could get a gltf with separate textures so I can inspect it more easily.

**Comment by pushmatrix** [comment]
Scrape the model from the src here: https://best-deltadromeus.glitch.me/

That one is very pronounced with the stitching.
