### ISSUE TITLE
NPM Install issue after cloning repository

### ISSUE THREAD

**Issue by KingYapster** [GoogleWebComponents/model-viewer#732]
After cloning the model-viewer repository, as per the instructions I did npm install. Which led to the issue in the screenshot below!

![image](https://user-images.githubusercontent.com/49189210/63915995-0667af00-ca55-11e9-8d37-2d23dbcadf77.png)
![image](https://user-images.githubusercontent.com/49189210/63916004-1089ad80-ca55-11e9-8622-d3d072f9342b.png)

**Comment by cdata** [comment]
Hey @KingYapster thanks for reporting. We all use Linux / Macs to develop over here, so we haven't tested our development setup on Windows much. That said, it looks like you might be able to do a successful install from the Linux shell. Have you tried that?

**Comment by cdata** [comment]
@KingYapster I'm going to close this in favor of #805 , which will track Windows / NPM compatibility.
