### ISSUE TITLE
Using multiple materials in AR

### ISSUE THREAD

**Issue by Dmitrijsmok** [GoogleWebComponents/model-viewer#734]
Is there any way to load multiple materials and textures for one object into AR scene? or I should bake all into one file?
I use Blender 2.8 and I have issues in the Canary, but only in AR view

**Comment by cdata** [comment]
@Dmitrijsmok Thanks for reporting. Could you share screenshots of what you expect and the issues you are seeing?

**Comment by Dmitrijsmok** [comment]
@cdata Hey, try to reproduce this issue and seems like it is already fixed. Now I am able to make different textures and materials in one object.
