### ISSUE TITLE
Model viewer not working on modal view with Bootstrap

### ISSUE THREAD

**Issue by iburguera** [GoogleWebComponents/model-viewer#735]
### Description

Model viewer is not working properly on modal view with bootstrap, the GLB object is not showing. It works properly when the code is outside the modal view. 

#### Live Demo
https://codepen.io/iburguera/pen/bGbrLYa

### Tested on 
- [ x ] Chrome
- [ x ]  Firefox
- [ x ]  Safari

### OS
- [ x ]  MacOS

### Versions
- model-viewer: v0.6.0
- three.js: r104
- Bootstrap: 3.4.0

UPDATE: (03/09/2019) The code works properly on version 0.3.0 but not in the following versions.

**Comment by cdata** [comment]
@iburguera thanks for the report. I suspect this could related to the `modelIsVisible` bug #524 . I'll make sure to take a look at it as we handle #524 for the v0.7.0 release.

**Comment by iburguera** [comment]
Thank you very much Christopher! I will use the v0.3.0 instead until the bug is fixed. BR
