### ISSUE TITLE
DoubleSided materials render incorrectly in some Android devices after 0.6.0

### ISSUE THREAD

**Issue by mrdoob** [GoogleWebComponents/model-viewer#740]
### Description

On some Android devices smooth surfaces appear to be way too shinny after 0.6.0

Devices tested/affected: Galaxy Note 4, Galaxy S8, Pixel 3, Pixel 3a and Nexus 6p.

![Screenshot_20190905-075818](https://user-images.githubusercontent.com/97088/64376843-09771800-cfde-11e9-993f-694dabb9d2aa.png)

#### Live Demo
http://model-viewer-tester.glitch.me/

### Browser Affected

- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.6.0

**Comment by elalish** [comment]
This is very strange. First, the problem only appears with the last of four meshes in the file. The color is gone because the diffuse light is down to nearly zero anywhere that is facing a light source (but only on Android). The glb you exported has lost most of the texture detail, so I'm working from the original glTF, but it exhibits the same behavior. I thought at first it might be a gl precision issue, but that's had no effect.

**Comment by mrdoob** [comment]
> This is very strange. First, the problem only appears with the last of four meshes in the file.

😮

**Comment by mrdoob** [comment]
Hmm, that was an interesting observation. It made me spectorjs it and, it seems to me that the problem is with the first drawcall.

<img width="1209" alt="Screen Shot 2019-09-06 at 3 39 39 PM" src="https://user-images.githubusercontent.com/97088/64464406-ae682280-d0bc-11e9-8917-4a4feeb54b9f.png">

**Comment by elalish** [comment]
Two questions: first, how do you spectorjs your phone? second, what error are you seeing?

**Comment by mrdoob** [comment]
Well, it just so happens that... from all the models available in http://model-viewer-tester.glitch.me/ this one is the first one that doesn't draw in a single drawcall.

**Comment by mrdoob** [comment]
> Two questions: first, how do you spectorjs your phone? second, what error are you seeing?

You can't spectorjs your phone. And I'm not seeing any error. I just noticed that the mesh that is being drawn first is the one that appears metallic in the phone.

Welcome to the sad world of lack of WebGL debug tools 🙌

**Comment by elalish** [comment]
ah, that is interesting. Thanks.

**Comment by mrdoob** [comment]
I'm going to look for more glb models that have multiple parts.

**Comment by mrdoob** [comment]
I've added Lantern which has multiple parts and it renders fine on mobile... 😑
