### ISSUE TITLE
Interaction prompt appears even when camera controls are disabled

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#741]
The interaction prompt appears automatically as of #623 . Unfortunately, it now appears even when the camera cannot be controlled (in other words, when the model is not interactive).

Test case for the problem: http://lopsided-motion.glitch.me/interaction-prompt.html

**Comment by cdata** [comment]
`macOS 10.13 safari 12.1  ✖ test/ » ModelViewerElementBase with ControlsMixin » when registered » camera-controls » a11y » when configured for focus-based interaction prompting » does not prompt users to interact before a model is loaded` is flakey, and it looks like this could be related.

Moving this back into 0.7.0.

**Comment by elalish** [comment]
Also, we're missing "none" as an option for interaction-prompt on the front page.
