### ISSUE TITLE
Is it possible to add extra buttons/links to the scene/ar viewer?

### ISSUE THREAD

**Issue by HugoKampsSB** [GoogleWebComponents/model-viewer#745]
Hello,

First of all, I love this webcomponent. As a Unity AR/VR developer it is amazing to see such an easy implementation for AR in webpages, with so many possibilities.

Now to my question: I was wondering if it is possible to customize the model-viewer itself, like giving it extra button to different links in the bottom. Currently it only shows a button to go back to the webpage you came from, but it would be great if I could add more links.

Thanks in advance and keep up the great work!

**Comment by cdata** [comment]
@HugoKampsSB It's definitely possible to customize `<model-viewer>`, but `<model-viewer>` (the HTML tag) is not the same thing as Scene Viewer (the native app that launches when you press the AR button on Android).

If you want to customize Scene Viewer, I'm afraid that is not possible at this time.

However, if you want to customize `<model-viewer>`, the sky is the limit. And, if you hit a limitation, we will probably do what we can to remove that limitation in a future version 👍

**Comment by cdata** [comment]
It's also worth noting that `<model-viewer>` will be gaining a lot of the AR capabilities of Scene Viewer over time, as the WebXR standard starts to solidify and implementations land in browsers.

**Comment by HugoKampsSB** [comment]
Thanks for your answer, and I was indeed talking about the native viewer. Good to hear about the plans for WebXR, I will watch the progress closely :)
