### ISSUE TITLE
Documentation typo & missing documentation on slots

### ISSUE THREAD

**Issue by cwervo** [GoogleWebComponents/model-viewer#748]
_Note: no demo/repro. steps because this is purely a documentation issue._

- [Animations docs page](https://googlewebcomponents.github.io/model-viewer/examples/animation.html) has a missing space typo: "theautoplay"
- Missing documentation on [slots](https://github.com/GoogleWebComponents/model-viewer/blob/master/src/template.ts#L240-L284)

Will submit a PR soon addressing these issues.

**Comment by cwervo** [comment]
@cdata Made a PR for this, but looks like it's failing for reasons I can't discern 😬

**Comment by cdata** [comment]
@cwervo my apologies, our testing infrastructure is in a state and we need to update our Travis config to fix it. Basically the same issue that precipitated this: https://github.com/webcomponents/polyfills/pull/200

**Comment by cwervo** [comment]
@cdata Ahhh, gotcha — okay, will check in again next week then — have a good weekend!
