### ISSUE TITLE
Way to change 3D model and/or materials dynamically

### ISSUE THREAD

**Issue by vortice3D** [GoogleWebComponents/model-viewer#752]
Hi there:

In order to accomplish an upcoming AR project with ARCore I'm hesitating between a native app focus on the one hand, and a (probably PWA) web app on the other.

After reviewing the docs, my main doubts on using the second option (of course using this model-viewer component) are focused in the not existence of public APIs intended to change dynamically the 3D model, or al least its materials.

Any info on this?

Best regards.

**Comment by cdata** [comment]
@vortice3D this is definitely something we are planning to add. We have a few issues that have come up asking for this capability along different dimensions, and recently I filed https://github.com/GoogleWebComponents/model-viewer/issues/738 to start to describe how we might enable this.

Unfortunately, that doesn't give you much to work with right away. If you are feeling ambitious, I would recommend trying to install this project as an NPM module and "rolling your own" custom element out of it. You can find a blueprint for how we piece the element together from various mixins in https://github.com/GoogleWebComponents/model-viewer/blob/master/src/model-viewer.ts#L16

**Comment by vortice3D** [comment]
Hi **cdata**:

Thanks for your answer and advice. From here I'm going to have a look at the referred file.

As said I think in a potential winning workflow with Scene Viewer under a PWA development on Android/iOS, and using BabylonJS as WebGL Engine (I prefer it over ThreeJS).

Best regards.
