### ISSUE TITLE
UpdatingElement sets a remove attribute as 'null' for string properties

### ISSUE THREAD

**Issue by jsantell** [GoogleWebComponents/model-viewer#76]
This seems unexpected, should investigate more, but a string property is reflected as `undefined` on initialization (e.g. for attribute 'foo', `this.foo` is undefined). After setting the property, and subsequently removing (`removeAttribute('foo')`), the reflected value is now stringified null, e.g. `this.foo === 'null'`.

This is unexpected reflection for representing the same state: an element that does not have the attribute in question.

**Comment by cdata** [comment]
Quick update: looks like this was fixed in December via https://github.com/Polymer/lit-element/pull/369 and released in v0.7.0 of lit-element
