### ISSUE TITLE
AR Mode not working in Dev Environment 

### ISSUE THREAD

**Issue by jeansusgodney** [GoogleWebComponents/model-viewer#766]
### Description
Hi, I just cloned the project on my local dev environment without any code modified. But it seems the AR mode is not working at all. I have tried with Android Chrome (Galaxy S9) and iOS Safari (iPhone 7). When I tapped on the AR Mode, it only shows me the model and the permission to ask the camera is not even shown. 

### Browser Affected

- [x] Chrome
- [x] Safari

### OS

- [x] Android
- [x] iOS

**Comment by cdata** [comment]
@jeansusgodney Thanks for the report. We have a pending bug for iOS 13 right now, see #758 .

For Android, you must serve the model from an `https://` origin in order for Scene Viewer to launch. Can you confirm that you are doing this?

**Comment by jeansusgodney** [comment]
thanks. It works
