### ISSUE TITLE
Announcement text visible in High Contrast mode

### ISSUE THREAD

**Issue by svinkle** [GoogleWebComponents/model-viewer#767]
### Description

The `model-viewer` screen reader live announcement text is visible in [Windows High Contrast ](https://support.microsoft.com/en-ca/help/13862/windows-10-use-high-contrast-mode)mode. This could lead to a confusing user experience as to why this text is visible for low-vision users.

```html
<p role="status" style="position: absolute; color: transparent; margin: 0px; left: 0px; top: 0px; pointer-events: none;">All 3D models in the page have loaded</p>
```

**Recommendation:** Apply the [`.sr-only` CSS class](https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/main.css#L122) to visually hide the text. Applying a `transparent` color to an element renders the element as visible using native theme colors in High Contrast mode.

#### Live Demo

![Screen Shot 2019-09-23 at 2 45 12 PM](https://user-images.githubusercontent.com/1392632/65453512-59910f80-de11-11e9-9555-0e8357f18059.png)

### Browser Affected

- [ ] Chrome
- [x] Edge
- [ ] Firefox
- [ ] Helios
- [x] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### Versions

- model-viewer: v0.6.0

**Comment by cdata** [comment]
Thanks for the find and the recommendation @svinkle !
