### ISSUE TITLE
FOV not acting like a real camera

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#768]
### Description

It seems like adjusting fov only adjusts how zoomed in you area. Changing FOV should distort the proportions and perspectives, but all it seems to do is zoom in and out.

Here is it working on Sketchfab:

### 10 degree FOV on Sketchfab
<img width="758" alt="Screen Shot 2019-09-24 at 10 19 40 AM" src="https://user-images.githubusercontent.com/190692/65520203-3881fa80-deb5-11e9-9b3d-6b476b7cc0db.png">

### 45 degree FOV on Sketchfab
<img width="723" alt="Screen Shot 2019-09-24 at 10 19 29 AM" src="https://user-images.githubusercontent.com/190692/65520289-59e2e680-deb5-11e9-9381-f8b73ff79fc9.png">

### 60 degree FOV on Sketchfab
<img width="733" alt="Screen Shot 2019-09-24 at 10 19 34 AM" src="https://user-images.githubusercontent.com/190692/65520258-4a639d80-deb5-11e9-80f0-8688cb303621.png">

And here it is on model viewer.

### 10 degree FOV
<img width="421" alt="Screen Shot 2019-09-24 at 10 20 29 AM" src="https://user-images.githubusercontent.com/190692/65520346-6c5d2000-deb5-11e9-9bd4-7ac9f8e3e63f.png">

### 45 degree FOV
<img width="402" alt="Screen Shot 2019-09-24 at 10 20 37 AM" src="https://user-images.githubusercontent.com/190692/65520362-71ba6a80-deb5-11e9-9c1c-7edfe661586a.png">

### 60 degree FOV

<img width="416" alt="Screen Shot 2019-09-24 at 10 20 42 AM" src="https://user-images.githubusercontent.com/190692/65520371-754df180-deb5-11e9-8489-db576e5aeb24.png">

### Steps to reproduce.

Go here: https://unite19.myshopify.com/products/indie
Inspect the element for the model-viewer and add in the field-of-view attribute.

You'll notice that while FOV does zoom in the model, it does not provide the correct perspective distortion for that FOV.

### Browser Affected
All

### OS
All

### Versions
- model-viewer: v0.6
- three.js: r105

**Comment by elalish** [comment]
It looks a little like fov is having no effect. Can you give specific repro steps for you’re creating these images?

**Comment by pushmatrix** [comment]
@elalish  I added the steps above.

**Comment by elalish** [comment]
Thanks. Actually, what distorts perspective is the distance of the camera to the object. Fov is a purely linear transformation, so it only scales the width of the viewport. sketchfab is likely changing the distance along with the fov to keep the model filling the viewport, hence the perspective change. Does that make sense?

**Comment by pushmatrix** [comment]
That does make sense. My assumption though was that changing the FOV and then zooming in to position to change the distance would result in the perspective change in model-viewer.

The reason I'm looking for this is that some merchants have asked about changing FOV for some products, and they were surprised when all it did was zoom in / out.

**Comment by elalish** [comment]
Ah yes, that used to be true when we zoomed by changing radius. I switched to zooming with FOV because it actually works better in several ways. However, the radius is configurable in camera-orbit, and that should have the effect they desire. Please take a look at the precise framing PR, since that also adds a way to specify radius as %, which might make this easier.

**Comment by pushmatrix** [comment]
Ohhh I see where my confusion was coming from. I would set the field-of-view, and then use the mouse wheel to zoom out. I thought zooming was changing the radius, but it was instead changing fov. Gotcha.
