### ISSUE TITLE
Model-viewer does not prevent scroll in horizontal carousels

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#794]
### Description

By default the model viewer hijacks mouse / touch movements. Meaning you can't scroll down the page when your finger is on it. This is intended.

However in carousels, it seems like the model-viewer is not preventing horizontal movement:

![carousel](https://user-images.githubusercontent.com/190692/66082922-336a1e80-e539-11e9-97ed-3e0a928456c0.gif)

It should act the same horizontally as it does vertically to be consistent.

#### Live Demo
Check it out here: https://steep-possum.glitch.me

### Browser Affected
All browsers

### OS
All OS

### Versions
- model-viewer: v0.6.2
- three.js: r108

**Comment by cdata** [comment]
@pushmatrix it appears that you are using a content-script-based scrolling technique here. If you try a similar example that uses native browser scrolling, you will find that scrolling is stopped as intended (see http://lopsided-motion.glitch.me/horizontal.html for an example).

What I would recommend is that your carousel code respect the `event.defaultPrevented` property, which should be set to `true` in the case that the model is being interacted with. The intention of our code is not to hide the event (this can actually cause conflicts with other libraries that observe events for non-interaction purposes). We only intend to stop the default behavior of the event, which in this case is scrolling.

**Comment by pushmatrix** [comment]
Agreed. Closing.
