### ISSUE TITLE
Models do not render on some low-end devices

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#797]
`<model-viewer>` v0.5.1 | `<model-viewer>` v0.6.2
-------------------------|---------------------------
![image](https://user-images.githubusercontent.com/240083/66244040-853ab200-e6bb-11e9-8fab-8dc2e26f57d7.png)|![image](https://user-images.githubusercontent.com/240083/66243896-0f364b00-e6bb-11e9-94bf-dd3e5ea74bf6.png)

It looks like between v0.5.x and v0.6.x we regressed significantly on low-end devices. Chrome on Nexus 5 no longer renders, and anecdotally we have heard that KaiOS devices that render in v0.5.x no longer render in v0.6.x.

Pictured above is a Nexus 5 with Chrome 76 stable on Android 4.4.

**Comment by cdata** [comment]
cc @mrdoob @elalish

**Comment by cdata** [comment]
Anecdotally, it sounds like WebGL is crashing on Nexus 5. I haven't confirmed this yet, but another user mentioned it to me.

**Comment by mrdoob** [comment]
Anything done with WebGL is crashing? I don't have my arsenal of phones with me at the moment.
