### ISSUE TITLE
Update controls prompt icon hand SVG to work with all types of models

### ISSUE THREAD

**Issue by maaslalani** [GoogleWebComponents/model-viewer#817]
### Description

The current hand icon svg isn't easily visible for some models. For example, a model that has a lot of white will make the prompt hard to see:

https://abalone-diplodocus.glitch.me/

One solution would be to allow the hand colour to be customized, but that won't work in cases where the model-viewer doesn't know what the input glb will be in advance.

A better solution is to have an icon that works in all scenarios, regardless of background and model materials. 

What do you think of something like this:

![image](https://user-images.githubusercontent.com/42545625/66602072-5454f400-eb77-11e9-9c64-f66736b4b81a.png)

<table>
<tr>
<th>Proposal</th>
<th>Current</th>
</tr>
<td>
<img width="568" alt="Screen Shot 2019-10-10 at 3 38 05 PM" src="https://user-images.githubusercontent.com/42545625/66600709-1e624080-eb74-11e9-80b7-1b64299309c9.png">
</td>
<td>
<img width="585" alt="Screen Shot 2019-10-10 at 3 38 58 PM" src="https://user-images.githubusercontent.com/42545625/66600710-1e624080-eb74-11e9-9039-3effc5082aae.png">
</td>
</tr>
<tr>
<td>
Demo: <a href="https://elite-pincushion.glitch.me/">https://elite-pincushion.glitch.me/</a>
</td>
<td>
Demo: <a href="https://translucent-lunch.glitch.me/">https://translucent-lunch.glitch.me/</a>
</td>

</tr>
</table>

**Comment by cdata** [comment]
🤷‍♂ I like the proposed one, subjectively speaking. It's nice that it has a contrasting outline. WDYT @elalish ?

**Comment by elalish** [comment]
I like it a lot. I'd take a guess they've put more thought into it than we ever did.

**Comment by cdata** [comment]
That would be an insensitive guess, but you do you.

**Comment by elalish** [comment]
Sorry, I just mean they have more resources dedicated to UX design than we do (at least currently).

**Comment by cdata** [comment]
@maaslalani @pushmatrix is it okay just to take the icon from your demo Glitch? Are you gifting that to our project?

**Comment by pushmatrix** [comment]
@cdata We are gifting it :), but let us trim it down a bit. I think it has emojis and in the svg for some reason and lots of extra cruft.
