### ISSUE TITLE
Loading progress state thrashes on initial configuration

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#847]
You can see from our progress bar that the reported loading state is thrashing on first load. It jumps from 0 to 1 really fast and then jumps back down to 0 and loads normally. We should fix this to remove the thrashing.

Here is a slowmo GIF of the visual artifact created by the thrashing state:

![progressbar](https://user-images.githubusercontent.com/240083/67323729-ba227380-f4c7-11e9-9098-5de9ab9ac095.gif)

**Comment by pushmatrix** [comment]
Oh strange, I am noticing that too but haven't seen that before.

**Comment by pushmatrix** [comment]
Is there an interim workaround for this? 

We have one merchant with a custom progress ring, and it looks real wonky:

![ring](https://user-images.githubusercontent.com/190692/67407299-49da2780-f585-11e9-8209-1d97d79eff3d.gif)

Like is there a way to look at progressevents and see if they are bogus?

**Comment by cdata** [comment]
The best I can offer is to debounce so that you only act on the events after a certain threshold. I schedule a v0.7.1 release for this so a fix should go out soon.

**Comment by pushmatrix** [comment]
A certain threshold of time or of progress loaded?

**Comment by cdata** [comment]
It would be time. The symptom seems to be that we dispatch progress ahead of property configuration, so I expect the first small handful of events that go from 0 - 1 to happen very quickly.

**Comment by cdata** [comment]
Looks like this is only happening when the generated environment map is used.

@pushmatrix you might be able to mitigate the effect by using an external `environment-image`.

**Comment by pushmatrix** [comment]
Ah good find.

The debounce works fine since the events are indeed like 1 ms apart.
