### ISSUE TITLE
Viewing generated gltf model in AR?

### ISSUE THREAD

**Issue by MiikaH** [GoogleWebComponents/model-viewer#852]
Hey,

Is there a way to view javascript generated model in AR viewer? When I pass a gltf/glb file as Data URL to model-viewer it loads fine in the webgl viewer, but AR button navigates browser to `about:blank#blocked`.

Quick investigation makes me suspect that data url syntax is messing with the `intent:` link used to launch ArCore viewer. Is there any way to make dynamically generated gltf models work in AR or is that simply impossible?

**Comment by cdata** [comment]
Hey @MiikaH , this is not currently supported by Scene Viewer, and I don't think they plan to support it in the near future. Your best option is to save the generated model to a server that hosts it on a secure origin, and then when it has been saved, try to load it in Scene Viewer.
