### ISSUE TITLE
AR is not working on Android devices (couldn't load object)

### ISSUE THREAD

**Issue by bankey1443** [GoogleWebComponents/model-viewer#853]
### Description

Attempting to use the model-viewer in our project, and it works wonderfully on desktop and iOS. However, I am unable to get the AR aspect to work on our android devices. Displaying the 3d-objects works fine, but when we tap on the AR button it seems like it attempts to load the Scene Viewer but just displays "Couldn't load object".

For the model-viewer src, I have tried using both `https://...` paths and relative paths to the directory that contains the `.gltf` file. We currently have three separate 3d-models for testing purposes, and they all have the same issue. Right now we are using the bundled build and adding script tags to the page we want to display the 3d-models.

#### Live Demo
The following demo is pretty close to what we have on our test page. We have been removing the 'optional' js (and required `webcomponents-loader.js` pertaining to Edge/Firefox support) but decided to leave it in for the demo.

Note that we are in the early stages of implemented 3d-model functionality on our website, and the `.bin, .gltf, and .usdz` files we currently have are rather large (the model in the demo has a `.usdz` file that is around 15MB and the `.bin` file is around 10MB, so at its current state can eat up data plans pretty quickly):

https://entertaining-bosworth.glitch.me/

### Browser Affected
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS
- [x] Android (Galaxy S7 and S10, both Android 8.0+)
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: 0.7.1, although we couldn't get it to work using 0.7.0 as well

**Comment by cdata** [comment]
@bankey1443 thanks for reporting, and for the test case. It looks like this is probably a Scene Viewer compatibility bug of some kind. I will report to the Scene Viewer team and update this thread as I learn more.

**Comment by bankey1443** [comment]
@cdata thank you for getting to this so quickly. As a follow-up, I cloned the repository and added my 3d-model files for testing purposes. I made a bare-bones test page

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no,minimum-scale=1.0, maximum-scale=1.0">
    </head>
    <body>
        <model-viewer src="assets/ChromeHandle/NEW_Chrome_handle.gltf"
                      ios-src="assets/ChromeHandle/NEW_Chrome_handle.usdz" ar auto-rotate camera-controls
                      quick-look-browsers="safari chrome" background-color="#222">
        </model-viewer>

        <!-- Loads <model-viewer> for modern browsers: -->
        <script type="module" src="https://unpkg.com/@google/model-viewer@v0.7.1/dist/model-viewer.js"></script>

        <!-- Loads <model-viewer> for old browsers like IE11: -->
        <script nomodule src="https://unpkg.com/@google/model-viewer@v0.7.1/dist/model-viewer-legacy.js"></script>
    </body>
</html> 
```

I ran `npm run serve` and exposed my local so I can access it with my mobile test devices. Following these steps I was able to get the AR working on my Android devices. Am I missing some dependencies? I'm not sure why it would work this way and not in the glitch.me demo

**Comment by cdata** [comment]
@bankey1443 that's very strange, I would actually expect the opposite. Scene Viewer is supposed to have trouble with `localhost` origins.

I filed this bug internally with the Scene Viewer team. Meanwhile, you can use this web-based Scene Viewer test tool (currently in beta) to get some feedback on the model: https://vr.google.com/scene-viewer-preview

I noticed it outputs some warnings with the test model you provided above: 
![image](https://user-images.githubusercontent.com/240083/67594227-b9cce700-f718-11e9-8e84-2f9f7d99ad7f.png)

**Comment by abyra-cjpony** [comment]
@cdata As a minor follow-up, I did use the test tool on the model and I received the same warning about the maximum number of triangles. The other sample models that we have came back with no errors. Unfortunately that's all I have to provide at this point; I'll continue to keep trying on my end.

**Comment by cdata** [comment]
@abyra-cjpony are you also experiencing problems displaying your models in Scene Viewer?

For those of you with issues, do the models render in the web-based Scene Viewer test tool?

**Comment by bankey1443** [comment]
@cdata Oh my fault, was using a separate account outside of my work account. Both accounts are mine; sorry for the confusion. The web-based Scene Viewer I tried three different models on, and 2/3 returned no errors (I tested a sample Khronos file as well and it did not return any errors), but none of them rendered in the browser. I just assumed that since it was in beta that it was not showing the model in the browser, but if it is supposed to display the file, then it did not work.

**Comment by cdata** [comment]
@bankey1443 oh, thanks for clearing that up 😅 

Scene Viewer and `<model-viewer>` currently use different model loading and rendering backends. The web based tool I linked you to uses a backend that is very similar to Scene Viewer, so if it doesn't render there it probably won't render in Scene Viewer either.

Thanks for confirming the issue. The Scene Viewer team has prioritized this bug, so hopefully we will have some feedback for you soon (although they are a different team and I cannot make promises about when they will get to it).

**Comment by bankey1443** [comment]
@cdata sounds good, thank you for the quick replies. Let me know if I'm able to help out in any way.

**Comment by bankey1443** [comment]
@cdata I'm continuing to try to find a fix, although I am running out of ideas to try. Have others reported a similar issue, or is it just me that is having issues with Android devices? I figure that if others also had issue that they would be reported, although I haven't seen any other reports about this.

**Comment by bankey1443** [comment]
@cdata If it wasn't for other sample Khronos examples also not working I would be inclined to think that it would be a problem with the models we are using (tried using the Khronos DamagedHelmet which also does not render in the test tool.

I'm not familiar with how Scene Viewer works, but currently on our dev site we are using `src="https://hostname.com/path/to/gltf/file"` which has Cloudflare on it. Reading up on Scene Viewer I see that it should use local files over a secure connection which is what it seems like we are doing.

**Comment by cdata** [comment]
@bankey1443 Sorry, I may have missed an important detail. When you say the other Khronos models do not work, that doesn't match our expectations. Do those models work in the web-based test tool?

**Comment by bankey1443** [comment]
@cdata so I may have figured out the issue. I was wondering how the web-based test tool was able to render a model by simply using the `.gltf` file. The models that we originally received split out the images and buffer into separate files instead of having them embedded right in the `.gltf` file. I found a sample model that had all of the data embedded into the `.gltf` and ran it through the test tool which rendered successfully, so I tried it on glitch.com and it also worked 😃.

I didn't realize from how I originally received all of the files that the information should be right into the `.gltf` file. From taking a first look at it (and also having no prior knowledge with 3d-models) it looked like it was referencing the `.bin` and image files in the same directory as the `.gltf` file. That's probably why the Scene Viewer and test tool were originally failing as it wasn't looking at anything but the `.gltf` file. Is it possible to get it to work with the files being split out like that? If not, we'll get the models reprocessed.

**Comment by cdata** [comment]
Hey @bankey1443 is that the model that you showed us in the demo above?

**Comment by bankey1443** [comment]
@cdata correct. Both `.gltf` and `.bin` files are in the same directory.

**Comment by bankey1443** [comment]
@cdata update: on our test site we have tried `.glb` and both `.gltf` types (both embedded and with separate assets in the same directory).  We have verified that these are valid models by using the web-based test tool provided, along with hosting them on glitch.com and individually testing each one to make sure both 3d and AR work, which it **does** on glitch.com).

When we click/tap on the product image on our test site, it opens up a popup that contains the model-viewer (the popup is created when the image is clicked/tapped so the model-viewer is not on the page on page load). The AR button, on several Android devices, still displays the same 'cannot load object' error that we have been getting for some time now. We though it was an issue with Cloudflare, so we turned off Cloudflare on our site temporarily and retried, with no luck. All of the additional 'required/optional polyfill scripts are also being added to the page head.

I'm completely baffled as to why it doesn't work for us. I feel like I've tried everything, especially when it works on glitch.com.

**Comment by bankey1443** [comment]
Turns out Cloudflare was the issue. When accessing the `src` file via the URL, it displays on screen rather than starting the download immediately as I've seen on other websites. Once we turned off Cloudflare and waited for the changes to take into effect, it worked. Now we just need to figure out how to make the `src` file start downloading versus showing it in the browser.

Thank you for your help @cdata. Sorry for being such a pain with this.

**Comment by mattchiang777** [comment]
Hey @bankey1443, I'm running into this same exact issue you went through, except the production app is hosted on Google Cloud.

Hooking up my Pixel phone via adb, I get an error saying "invalid json". Copying and pasting the url where the file is hosted into the web browser does successfully download the .glb though.

Were you able to get AR Scene Viewer working? I couldn't tell if you got to that result from the last post.

**Comment by Hemanpreet** [comment]
I am using Model Viewer to display 3D model in AR. My model is getting displayed on iOS but not getting displayed on android. What can be possible reason and solution to this problem?

**Comment by elalish** [comment]
We won't be able to help with so little info. Please open a new issue and fill out the template completely, particularly the repro link, a screen recording, and any JS console errors/warnings.

**Comment by chandanwebkul** [comment]
Hi am reopen this issue 
Facing same issue with following details
I am using version 3.1.4.
It's working at my developer instance but at production instance it's not working.
Showing couldn't load object at android device
it's working on IOS, but  issue with android device
with chrome broswer.
I have checked cloudflare, i am not using cloudflare.
```html
<model-viewer style="margin: 0px auto; display: block;" data-js-focus-visible="" src="https://yodacart.com/shop/pub/media/catalog/product/glbmodels/TVLG006.glb" alt="A 3D model of an product" auto-rotate="" ar="" camera-controls="" touch-action="pan-y" shadow-intensity="1" camera-orbit="33deg 67deg auto" ar_preferred="" ar-modes="scene-viewer webxr quick-look" ar-status="not-presenting">
         <button id="ar-button" slot="ar-button" style="background-color: transparent;border-radius: 25px;
         border: 1px solid darkgray;position: absolute;bottom: 0px;right: 26%;">
            View In Your Space
        </button>
    </model-viewer>
```javascript
 setTimeout(() => {
            var link = document.getElementById('ar-button');
            link.click();
            console.log("click evnet occur");
        }, 3000);

``` 
```

**Comment by chandanwebkul** [comment]
```javascript
 setTimeout(() => {
            var link = document.getElementById('ar-button');
            link.click();
            console.log("click evnet occur");
        }, 3000);
```

**Comment by tobydevey** [comment]
In an html page, 3D model won't load in model viewer. I am getting:
'Couldn't load object - Looks like there's something wrong with this object.'
Sitting next to my visiting son, who has an identical Pixel 6 operating on the same version number software, we both load the page on our respective devices but get different results. 
His loads and works perfectly.
Mine does not. So it's not the object that's at fault.
I emptied the cache of the Google app, re-started my phone. 
Nothing seems to work but I am guessing that it relates to phone settings somehow.
Does anyone have any idea on what kind of phone settings may be responsible. My son is not here all the time so we cannot collaborate and compare easily.

**Comment by chandanwebkul** [comment]
Hello @tobydevey 
may be cause of third party any plugin or cache, 
you can verify this same code with another server or local server.

**Comment by tobydevey** [comment]
Thanks for your response @chandanwebkul.
As I said in my previous post, the model loaded and worked perfectly on an identical phone next to mine at the same time. The code is verified. Caches were emptied on my phone. Most recent version of Chrome installed.  Both phones on same broadband. The only difference between the phones was the provider but as I say both were being served data via the same broadband connection..

**Comment by diegoteran** [comment]
Hi @chandanwebkul,

We can help look into your issue: Please open a new issue and fill out the template completely, particularly the repro link, a screen recording, and any JS console errors/warnings.

**Comment by chandanwebkul** [comment]
Hi @diegoteran 
Thanks for consider my issues.
But Now issue is resolved, issue due to third party cache server. 
I have doubt regarding why cache/server effect on this feature. so i am checking.
If i get any thing proper solution definitely share with you.

**Comment by tobydevey** [comment]
Update on my situation may help others.
My problem was that some of the textures were procedural. I baked some and simplified others and now the object loads with ease.
