### ISSUE TITLE
Model Viewer Requests

### ISSUE THREAD

**Issue by aiursrage2k** [GoogleWebComponents/model-viewer#857]
The model viewer is great, but the functionality is really limited. Not having to make the AR content in an app will really make it more scaleable. 

It would be great if we can add more functionality, some basic buttons being able to play more then 1 animation, if you want realistic models you will need to increase the poly and texture count (especially for something like realestate).

**Comment by cdata** [comment]
@aiursrage2k Thanks for the feedback. I think you may be thinking about Scene Viewer, which is the native app that `<model-viewer>` launches for AR on Android devices. `<model-viewer>` does not have a strict poly limit, and the texture count is limited by the browser so we can't control that. `<model-viewer>` also supports any custom UI you want, and as many animations as you want.

**Comment by aiursrage2k** [comment]
Well apple already has reality composer and with that you can create basic AR content without requiring an app.

**Comment by aiursrage2k** [comment]
Can we modify the source code, is this simply using a modified version of threejs?  Can I do things with the raycaster when its selected the model in AR?
https://threejs.org/docs/#api/en/core/Raycaster

**Comment by cdata** [comment]
Yah, please do! It's an open source project and we hope folks will experiment with the source. From a high-level, we are just a web component wrapper for Three.js APIs. So if you are familiar with Three.js, it should be easy for you to modify the renderer internals.

**Comment by aiursrage2k** [comment]
Okay great. Theres 1 more issue for whatever reason the AR part of the app isnt working for example I have a simple html using the viewer, I enabled the AR flag but when I try to open it using google chromium it just takes the model into fullscreen mode -- I dont see the option to put into AR. I know it can work because in the actual google demo it does work.

For example the link below does not allow me to take the model into AR mode, whereas the modelviewer link does work -- is there something else missing?
http://178.128.237.107/test0/test0.html
https://modelviewer.dev/examples/augmented-reality.html
```
<html>
         <head>
                     <title>3D Test</title>
<script type="module" src="https://unpkg.com/@google/model-viewer@0.5.1/dist/model-viewer.js">
                     </script>
                           </head>
                             <body>
                                         <model-viewer src="assets/Astronaut.glb" camera-controls autoplay background-co
lor="#70BCD1" shadow-intensity="1"
                                stage-light-intensity="3" environment-intensity="2" ar width="800px" height="600px"
                                ></model-viewer>
                                           </body>
</html>
```

**Comment by aiursrage2k** [comment]
Right now I am just using the CDN version of the model viewer, is there anyway to get access to the threeJS scene/camera or to instantiate the model-viewer using javascript?

**Comment by cdata** [comment]
@aiursrage2k yes, you would have to clone the project repo, install the dependencies and build it (per the instructions in our README). From there, you can make changes to the code and re-build it as needed.

We have plans for a public API that would allow you to do similar things without building the library yourself. See #738 for more details on that.

**Comment by aiursrage2k** [comment]
Yeah that sounds about right. I was playing around with "Adobe aero" today, almost  a clone of the reality kit. I am little worried everything will be locked into a very limited functionality set unless we expand it to be more expansive.
