### ISSUE TITLE
Responsive poster images

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#860]
Picking a "one size fits all" poster image is not really bandwidth friendly when considering different resolutions. For mobile we might want 400px while for larger screens we might want 1200px.

Thoughts on supporting something like images do with srcset?
```
<model-viewer poster="elva-fairy-320w.jpg 320w,
             elva-fairy-480w.jpg 480w,
             elva-fairy-800w.jpg 800w">
```

The workaround for now is to not set a poster, and then define poster images via media-queries with `--poster-image` css variable.

**Comment by cdata** [comment]
@pushmatrix I think ideally I would want to lean on what the browser gives us for this. Something along the lines of:

```html
<model-viewer>
  <img slot="poster" srcset="elva-fairy-320w.jpg 320w,
                             elva-fairy-480w.jpg 480w,
                             elva-fairy-800w.jpg 800w"
                     sizes="..."
                     alt="...">
</model-viewer>
```

If that doesn't already work as intended, then we should do what we can to make it ergonomic and useful. WDYT?

**Comment by mikkoh** [comment]
Would be good to document this somewhere if it works

**Comment by cdata** [comment]
Yeah, we recently added a page in our docs about slots, but the slots are not comprehensively enumerated yet https://googlewebcomponents.github.io/model-viewer/examples/customizing-ui.html

We should definitely add some docs for that stuff.

**Comment by cdata** [comment]
@pushmatrix @mikkoh just want to follow-up here, did y'all try out using `<img slot="poster">`?

**Comment by pushmatrix** [comment]
Last week when I tried to test it, unpkg was down. This week when I tried to test it, glitch is down. Lol.

Just tried it locally, and can confirm it works!

**Comment by cdata** [comment]
\o/

**Comment by cdata** [comment]
@mikkoh FYI filed this for better docs on this topic: https://github.com/GoogleWebComponents/model-viewer/issues/873
