### ISSUE TITLE
Problem accessing model-viewer.js today

### ISSUE THREAD

**Issue by areavisuale** [GoogleWebComponents/model-viewer#865]
### Description

Today model-viewer is not working. My website reports this error: 

`augmented-reality.html:1 Access to script at 'https://unpkg.com/@google/model-viewer/dist/model-viewer.js' from origin 'https://www.areavisuale.it' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I resolved for now loading the js in my server

#### Live Demo
https://www.areavisuale.it/en/augmented-reality.html

### Browser Affected

- [X] Chrome
- [X] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by cdata** [comment]
@areavisuale Thanks for reporting. We received another report of this (#866). I'll be using #866 as the primary tracking issue for this problem.

A workaround for the mean time seems to be to explicitly specify a version when linking to `model-viewer.js` from unpkg.com. So, for the latest version, it would be:

```html
<script type="module"
  src="https://unpkg.com/@google/model-viewer@v0.7.2/dist/model-viewer.js">
</script>
<script nomodule
  src="https://unpkg.com/@google/model-viewer@v0.7.2/dist/model-viewer-legacy.js">
</script>
```

**Comment by cdata** [comment]
This issue was deemed to be a temporary outage traced back to unpkg.com. Please refer to the discussion in #866 for details!

Thanks again for reporting @areavisuale and sorry for the disruption.
