### ISSUE TITLE
Make it possible to configure the background to be transparent

### ISSUE THREAD

**Issue by ethanny2** [GoogleWebComponents/model-viewer#874]
Sorry if this is not a relevant question but I couldn't find anything regarding this topic on the documentation/Internet. Is it possible to set the background-color attribute of <model-viewer> to transparent/ none? It appears to default to a white background if the CSS string is not parsed correctly.

**Comment by forresto** [comment]
Demo PR here, but it's WIP: https://github.com/GoogleWebComponents/model-viewer/pull/268 ... conversation: #182

**Comment by cdata** [comment]
@ethanny2 yes, we would like for this to be possible. It's a trickier problem than it seems, because it requires that we enable `alpha: true` the WebGL context, which in turn can have negative consequences for alpha blending in the scene.

So, all that to say I think we should support this but it needs to be opt-in.

**Comment by pushmatrix** [comment]
To add another usecase for this, Shopify allows merchants to specify the background colour over the model-viewer. However the poster image always gets generated with a white background. So if the background colours are different, you'll notice it when it transitions from poster -> 3D. It would be nice if we could generate the poster image as a png with a transparent background, that way we could seamlessly transition to the 3D model regardless of background color.

**Comment by matiasnombarasco** [comment]
Having this feature will help us a lot, currently, I haven't found any walkaround this behavior, so I can't this web component.
