### ISSUE TITLE
Lighting / colors load washed out, seem to fade to regular

### ISSUE THREAD

**Issue by forresto** [GoogleWebComponents/model-viewer#875]
On my 🥑 demo: https://3d-model-viewer-component.webflow.io/

When the model first loads, the colors / lighting look washed out:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/395307/68216475-f1585080-ffae-11e9-8d91-b77e7b11ab74.png">

After a few seconds it seems to fade to normal:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/395307/68216558-0d5bf200-ffaf-11e9-968b-a1f6835928a8.png">

What's going on here? HDR magic?

**Comment by cdata** [comment]
@forresto there is a subtle / semi-opaque white mask that is shown as part of the built-in loading progress indicator UI. It's possible that this is the culprit. Can you try hiding it by setting the CSS value: `--progress-mask: transparent`? Does that fix the issue for you?

**Comment by cdata** [comment]
Hey @forresto just following up here - did you have a chance to try hiding the progress mask with CSS?

**Comment by cdata** [comment]
@forresto I'm going to close out this issue for now. Hopefully the suggestion above helps, but if it doesn't then ping this thread and we can re-open it.
