### ISSUE TITLE
`ar` property should cover all ar types, not just scene viewer

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#882]
It's confusing that `ar` is for Scene-Viewer, while `ios-src` and `magic-leap` are device specific. 

Would it not make more sense for `ar` to enable / disable the badge regardless of device? I guess the worry there is someone could put `ar` but forget `ios-src`. 

Maybe the solution is to call `ar` something like `scene-viewer-ar`. Hmm

**Comment by cdata** [comment]
Yup, definitely agree with this. That's why we have #541 :)

**Comment by pushmatrix** [comment]
I'll close this in favour of that.
