### ISSUE TITLE
Draco compressed files not displaying

### ISSUE THREAD

**Issue by arberrexhepi** [GoogleWebComponents/model-viewer#884]
I have exported a .glb with DRACO compression from Blender and it is not showing up in model-viewer. Also scene viewer claims there is a problem with the object. Any ideas? I am trying to keep the file size down as much as possible.

**Comment by elalish** [comment]
See #72, this is on our short-term roadmap to support, but it's not in quite yet.

**Comment by cdata** [comment]
@arberrexhepi also to add to @elalish 's comment, Scene Viewer also does not currently support DRACO compression.

**Comment by cdata** [comment]
I'm going to close this in favor of #72 as we will be implementing DRACO support this sprint. Please follow along in the other issue!
