### ISSUE TITLE
Disable resize on AR

### ISSUE THREAD

**Issue by aviggiano** [GoogleWebComponents/model-viewer#894]
### Description

This is a feature request to provide an option to disable content resize on Augmented Reality, such as with [`allowsContentScaling`](https://developer.apple.com/documentation/arkit/arquicklookpreviewitem/3152993-allowscontentscaling?language=objc) on AR Quick Look.

**Comment by cdata** [comment]
@aviggiano thanks for the feature request! We'll see what we can do :)
