### ISSUE TITLE
PMREM shader compilation fails on some Alcatel devices

### ISSUE THREAD

**Issue by datkinsGoogle** [GoogleWebComponents/model-viewer#900]
### Description

Models on some low end devices appear to be loading in without textures (they show up completely black)

This was observed on an Alcatel TCL LX A502DL.  We loaded assets of different geo complexity using textures at different resolutions and noted the issue appears consistently.

It appears this is because it treats warnings as errors and doesn't like having a conditional texture lookup.

### Browser Affected

- [ X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.7.0
- three.js: rXX

**Comment by datkinsGoogle** [comment]
![errorlog](https://user-images.githubusercontent.com/48733093/69583640-33fac080-0f90-11ea-9cbb-044b31da2c67.png)

Adding screenshot of logs

**Comment by elalish** [comment]
Fixed by #920
