### ISSUE TITLE
Shadow regressions in latest master

### ISSUE THREAD

**Issue by soraryu** [GoogleWebComponents/model-viewer#939]
### Description
Shadow is now soft but clipped, and flips on auto-rotation.

To reproduce:
- open https://model-viewer-tester.glitch.me/
- select DamagedHelmet
- change shadow intensity to 1

![image](https://user-images.githubusercontent.com/2693840/71162152-fa456e80-224a-11ea-85dd-a558d059b56e.png)

**Expected**: shadow does not clip as when doing the same steps on https://model-viewer-tester.glitch.me/0.7.2.html
![image](https://user-images.githubusercontent.com/2693840/71162102-deda6380-224a-11ea-98a6-5a680c7195e4.png)

Additionally, activating "Auto Rotate" flips the shadow (which also doesn't happen in 0.7.2)
![image](https://user-images.githubusercontent.com/2693840/71162216-1ba65a80-224b-11ea-80fb-6acbe420c181.png)

@mrdoob haven't looked at your code, could the shadow flipping be a regression there vs. in model-viewer?

#### Live Demo
https://model-viewer-tester.glitch.me/ - uses latest master
https://model-viewer-tester.glitch.me/0.7.2.html

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

### Versions
master

**Comment by soraryu** [comment]
Isn't #940 only fixing the flip? What about the cutoff shadow?

**Comment by cdata** [comment]
@soraryu can you confirm that the problem still exists on the latest master? I just tried it out and could not reproduce the cutoff with our latest build.

**Comment by soraryu** [comment]
It was still present 2 hours ago when I tried but now it seems to be fixed on the above tester. Great!

**Comment by soraryu** [comment]
Sorry, have to report another shadow regression: shadows have stopped appearing on the last model (bike) on this page:
https://sleet-kookaburra.glitch.me/

**Comment by cdata** [comment]
@elalish I'm going to re-open this issue since it seems sufficiently generic, but we might want to start tracking separate issues for this stuff 🤷‍♂

**Comment by elalish** [comment]
@soraryu I can repro the issue with your bike model's shadow; it's very strange and I'll continue looking into it. I also noticed with your shark example; since it has such a large shadow region to cover, I'd recommend setting shadow-softness=0 or at least less than one. That will help you get back to a more reasonable resolution for such a small object in a large space.
