### ISSUE TITLE
Regression: white objects suddenly render yellow or blue

### ISSUE THREAD

**Issue by soraryu** [GoogleWebComponents/model-viewer#942]
### Description

Regression: white objects suddenly render yellow or blue.
Some parts of models that don't use textures have started to render yellow or blue.

![IMG_20191220_003317](https://user-images.githubusercontent.com/2693840/71218185-d9b7fb80-22c0-11ea-8100-b35cc1dc579e.jpg)
![IMG_20191220_003508](https://user-images.githubusercontent.com/2693840/71218187-dde41900-22c0-11ea-8c78-d9df09f0db7a.jpg)
![IMG_20191220_003300](https://user-images.githubusercontent.com/2693840/71218191-e177a000-22c0-11ea-8712-bb3ee6af8e48.jpg)

The bike parts above and the cubes around the shark are untextured and should render white; they did when I uploaded those models.

#### Live Demo
https://sleet-kookaburra.glitch.me/

### Browser Affected

- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [] Windows

### Versions

- model-viewer: latest

**Comment by cdata** [comment]
@soraryu I'm not able to reproduce this problem in your demo.

I have tried running the test case in Chrome 79 on Windows 10 via BrowserStack:

![image](https://user-images.githubusercontent.com/240083/71218848-ec5a1280-2277-11ea-8645-d59af3ad522a.png)

Can you offer any additional details about your setup? GPU? Windows / Chrome versions etc?

**Comment by soraryu** [comment]
Sorry, ticked the wrong OS. This happens on Android 10, Xiaomi Mi 9, latest Chrome.
![IMG_20191220_085002](https://user-images.githubusercontent.com/2693840/71238989-bd8a7d80-2305-11ea-9ddf-4dff24e4ffec.jpg)

**Comment by cdata** [comment]
## Reproduction attempts

Here are a few shots from phones on BrowserStack with the same chipset (Snapdragon 855) / browser (Chrome 79) combo:

Samsung Galaxy S10|Oppo OnePlus 7|
---------------------|----------------|
![image](https://user-images.githubusercontent.com/240083/71270436-6b962780-2306-11ea-8d27-12219b9e15f8.png)|![image](https://user-images.githubusercontent.com/240083/71270498-997b6c00-2306-11ea-9723-2f8202075246.png)

So, Samsung seems fine, but there definitely seems to be funky with the OnePlus. To my eyes, the lighting on those squares looks darkened in that render.

In the JS console, there isn't a whole lot of actionable info, although it does look like there are some non-power-of-two textures in the mix:

![image](https://user-images.githubusercontent.com/240083/71270776-448c2580-2307-11ea-9418-47c2ba6f0ad9.png)

For the OnePlus, I also saw this happening on the bike model, which looks pretty bad:

![2019-12-20 09-04-43 2019-12-20 09_06_47](https://user-images.githubusercontent.com/240083/71271963-51f5df80-2308-11ea-94b2-48b93b91f2ad.gif)

On both of those phones, these were the warnings I got in the console for the bike model, but only the OnePlus had major rendering issues:

![image](https://user-images.githubusercontent.com/240083/71271034-deec6900-2307-11ea-9d15-8acfb802ab8f.png)

Stepping back for a bit, I tried dropping the bicycle model into the Scene Viewer preview tool (https://vr.google.com/scene-viewer-preview) and noticed right away that [it has hundreds of errors](https://gist.github.com/cdata/ccf4f57d97d260cd43efbd04a7320da0) (as far as the preview tool is concerned) and also is reportedly very complex.

## Analysis

It seems like there is definitely a discoloration problem that we can reproduce. We can probably use the Oppo OnePlus 7 emulator on BrowserStack to isolate the problem and look into it. cc @elalish 

The yellow discoloration remains illusive. I guess we will need to get ahold of a Xiaomi 9 to verify the issue. It's possible that a fix for the Oppo will help the Xiaomi, but there is really no way to be sure.

As far as the bike is concerned, I'm worried that even if there is a `<model-viewer>` bug affecting it, it would be very difficult to tweeze it out of the nest of other problems in that model. @soraryu would you be willing to look into some of the errors reported by the Scene Viewer preview tool and let us know if you can reduce or eliminate them?

**Comment by soraryu** [comment]
Yep, I know the bike has lots of warnings, but until the 0.8 update has rendered fine in both model-viewer and SceneViewer on any device I tried (and that's a lot, ~20 different mobiles). Note that I have another issue open here (that you forwarded to the scene viewer team iirc) about the web preview being incorrect and models working fine on actual devices.

For reproduction, the shark is a much lighter model. I have an assumption what the issue is (affects all objects that don't have a texture assigned). I'll try to make a very simple repro.

**Comment by cdata** [comment]
Thanks @soraryu , and acknowledged that there are outstanding threads of discussion related to the bike.

I ordered us a Xiaomi Mi 9 for local testing, but we probably won't be able to do anything until after the new year.

**Comment by soraryu** [comment]
So this is definitely a regression between 0.7.2 and 0.8.0.

I uploaded a single white cube and it shows the same behaviour. I then made an array of cubes of varying smoothness / metallicness and the result is that all things that have 
a) no texture
b) metallic 0
are yellow.

You can switch model-viewer versions here (0.7.2/latest dist/master):
https://glitch.com/edit/#!/sleet-kookaburra

**Comment by elalish** [comment]
@soraryu Yes, I'd guess this is a regression we picked up from bumping our version of three.js. I'll look into it. I still need to find a device that repros it.

**Comment by soraryu** [comment]
Two more tests with external three.js look ok (of course I'm not sure that's the same version you're using):
![Screenshot_2019-12-20-21-57-31-215_com android chrome](https://user-images.githubusercontent.com/2693840/71291907-00833a00-2374-11ea-9f55-0cb12daafeb0.jpg)
![Screenshot_2019-12-20-21-58-29-562_com android chrome](https://user-images.githubusercontent.com/2693840/71291955-02e59400-2374-11ea-9597-ec4a6f73814f.jpg)

**Comment by cdata** [comment]
Ran into this issue on my Pixel 3 when looking at a demo from another unrelated issue (#950): https://model-viewer-dynurl-bug.glitch.me/

![Screenshot_20200106-084255](https://user-images.githubusercontent.com/240083/71832875-a87d5080-3060-11ea-9c68-2dd929bd90f7.png)

**Comment by elalish** [comment]
I built a minimal repro of this on three: https://github.com/mrdoob/three.js/issues/18315
