### ISSUE TITLE
Seeing purple noise when viewing assets in Model-Viewer 8.0 on a Pixel 3

### ISSUE THREAD

**Issue by datkinsGoogle** [GoogleWebComponents/model-viewer#947]
### Description

Noticed that, after updating a test page to use Model-Viewer 8.0, I am now seeing purple noise appear on the surface of that model.

#### Live Demo

Provided via DM

### Browser Affected

- [X ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.8.0
- three.js: rXX

**Comment by elalish** [comment]
This model did not pass the [glTF validator](http://github.khronos.org/glTF-Validator/). If you can reproduce the problem with a modified subset of the model that does pass the validator, please pass it along.

**Comment by elalish** [comment]
@datkinsGoogle Thanks for the version that passes the validator! I removed everything but the problematic body paint part and found that the problem only repros with shadows enabled. In addition, I found that even on non-Pixel devices, the shadow is incorrect for this model:
![image](https://user-images.githubusercontent.com/1649964/71749312-e93f5480-2e29-11ea-845d-6465e7b590b1.png)

**Comment by elalish** [comment]
Okay, the wrong shadow thing was mostly red herring and easily fixed. I'm seeing some strange color bugs though. Here is the originally reported bug, where we get purple noise in blocks on a Pixel 3, but only on one material (the only one I've kept here), which has an AOmap, but no other maps:
![image](https://user-images.githubusercontent.com/1649964/71834956-4a9f3780-3065-11ea-8181-1728ceaee66f.png)

Here it is with the AOmap removed (so no maps at all), and I'm getting a weird yellow color, which reminds me of #942:
![image](https://user-images.githubusercontent.com/1649964/71834741-c5b41e00-3064-11ea-8e9f-98dceccae798.png)
