### ISSUE TITLE
Non-static src urls always fails to fallback

### ISSUE THREAD

**Issue by wr0ngway** [GoogleWebComponents/model-viewer#950]
### Description

If I set the model-viewer `src` to a server side rendered url, the AR button fails to the fallback viewer.  If set to a public url it all works as expected.  All three options reference the same file: `public/box.gltf`

#### Live Demo

Hit the following url on chrome in android to demonstrate the issue:
https://model-viewer-dynurl-bug.glitch.me/

### Browser Affected

- [X] Chrome 79.0.3945.93
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android 10 (Pixel 4 XL)
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.8.0

**Comment by wr0ngway** [comment]
Note, when I originally ran into this issue, I was seeing the following rather than it dropping to fallback. I'm guessing this was because I was adding model-viewer through npm without all the support libs for fallback, but maybe it will provide some clues as to where things fail:
```
Unhandled Rejection (TypeError): fullscreen error

HTMLElement.[onARButtonContainerFallbackClick]

src/features/ar.ts:345

342 | 
343 | [$onARButtonContainerFallbackClick](_event: Event) {
344 | if (this[$arMode] === ARMode.AR_VIEWER) {
> 345 | this.requestFullscreen();
| ^ 346 | }
347 | }
348 | View compiled

HTMLDivElement.ARModelViewerElement.<computed>

src/features/ar.ts:195

192 | // were dispatched in the same handler as the fullscreen request. The
193 | // workaround is to split both effects into their own event handlers.
194 | // @see https://github.com/GoogleWebComponents/model-viewer/issues/693
> 195 | protected[$arButtonContainerFallbackClickHandler] = (event: Event) =>
| ^ 196 | this[$onARButtonContainerFallbackClick](event);
197 | 
198 | protected[$arButtonContainerClickHandler]: (event: Event) => void =View compiled

This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
```

**Comment by cdata** [comment]
@wr0ngway thanks for the report and the nice test case!

I think this is a case of Scene Viewer expecting a file extension on the glTF file. I made a fork of your demo here: https://elegant-maraca.glitch.me/

The only difference in my fork is that the non-static URLs have file extensions added to them. Give it a shot and let me know if that fixes your issue!

**Comment by wr0ngway** [comment]
Thanks for taking a look @cdata .  Good catch, this workaround seems to work for the Render URLs, though I'd imagine the Scene Viewer team would still want to hear about this as a bug?

Also, in the case of the Blob url, I don't know of a way add an extension there .  My original plan was to try to do everything client side, and I only reverted to server side rendering to see if I could figure out why those won't working :) .  Any ideas there?

**Comment by cdata** [comment]
Unfortunately, Scene Viewer does not support data URLs or object URLs. My understanding is that they do not intend to support the former, and the later is impossible due to the nature of object URLs and browser architecture.

/cc @tpsiaki to comment on requiring `.gltf` file extensions and whether or not there are plans to support data URLs in the future.

I'll also raise the question of file extensions internally and let you know if it would be considered a bug.

**Comment by wr0ngway** [comment]
Ok, thanks for the info.  I'll probably end up still generating the data client side, but maybe writing it to cloud storage as an intermediary.  Woulda been nice to skip the backend though :)

**Comment by cdata** [comment]
Browsing the official Scene Viewer guidelines, it is notable that the very first validation error pertains to missing file extensions: https://developers.google.com/ar/develop/java/scene-viewer

**Comment by cdata** [comment]
@wr0ngway would you be willing to elaborate a bit on your use case? It might be good anecdata for #738

**Comment by wr0ngway** [comment]
Ok, thanks, guess it isn't a bug then.  Surprising that file extensions still have such weight with all the other ways of specifying content types.

w.r.t my use case, I'm just playing around as a side project.  Wanted a simple tool to generate an AR view of arbitrary dimensions so that I could test fit things before buying :) . The exisiting apps never seem to have AR views of the pieces I want to buy, but they usually have dimensions, so I can throw up a box as an estimate.  I'm just using three.js to generate the model client side, then exporting to glTF and slapping it into model-viewer

**Comment by cdata** [comment]
Nice! FWIW this is definitely a flow we want to support with `<model-viewer>` standalone as WebXR begins to land more broadly. The gist would be that you can assemble multiple individual models into a scene (declaratively) and present them all at once in AR via WebXR.

**Comment by cdata** [comment]
Closing this, but we will definitely reference the feedback as we pursue #738 . Thanks!
