### ISSUE TITLE
Mesh ids not consistent between model-viewer versions.

### ISSUE THREAD

**Issue by fivelive** [GoogleWebComponents/model-viewer#952]
Is there a way to get a consistent ID for a specific mesh? By consistent I mean, an Id that is always the same (Whatever the three.js/mode-viewer version). Indeed, I realized that between v0.7.0 and v0.8.0, a same mesh had a different id for each version (mesh.id field). Also tried using the "uuid" of a mesh, it is also not consistent.

**Comment by cdata** [comment]
@fivelive for the purposes of API access, we consider Three.js to be an internal detail. So, while we don't prevent you from accessing Three.js objects, it is still considered part of our private API and therefor we offer no guarantee that it will remain stable over time.

That said, when we update our Three.js dependency, we do consider that a breaking change, so we will always mention it in the release notes. You can see that in the release notes for v0.8.0 we mentioned the Three.js upgrade towards the bottom as a breaking change: https://github.com/GoogleWebComponents/model-viewer/releases/tag/v0.8.0

In the long term, we are working on #738 where we will begin to offer concrete guarantees like the one you are requesting. You can follow along with some of the concrete work being done in #919 . Until then, please remember that when you access Three.js objects directly, it is the same as accessing private API and could break any time you update to a new version of `<model-viewer>`!

**Comment by fivelive** [comment]
It was stated in the release note, you are right! I do understand the risks now. Thank you! Keep it up!

**Comment by cdata** [comment]
NP, thanks for being understanding. I'll close this issue for now but please ping if you have additional questions or problems!
