### ISSUE TITLE
Poster image is offset if parent element has text-align: center

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#965]
### Description
I noticed that on 0.8.0, Bumbleride's posters appears offset:
<img width="1337" alt="Screen Shot 2020-01-20 at 10 03 35 PM" src="https://user-images.githubusercontent.com/190692/72773315-c906e800-3bd4-11ea-8ecf-41193e9662c0.png">

The loaded model is in the right spot though.

This must have something to do with the seamless transition work that was done in https://github.com/GoogleWebComponents/model-viewer/pull/890.

I narrowed it down to a parent element on the page having `text-align: center`. It seems like when that is set, the poster gets offset.

I made a Glitch of it here: https://mousy-target.glitch.me/

It's just a model-viewer wrapped in a div with `text-align: center`. Is this expected behaviour?
### Browser Affected
All

### OS
All

### Versions
- model-viewer: v0.8.0

**Comment by cdata** [comment]
Nice catch! Yah, this is definitely a bug, and was probably introduced in #924 when we made the built-in poster a `<button>` (which defaults to `display: inline-block`, and is thus affected by text alignment).

We'll get a fix out shortly.
